"""Generate the small shared TypeScript WebSocket contract from Pydantic."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pydantic import BaseModel

from .protocol import (
    ExtendTimeCommand,
    PingCommand,
    ServerEventEnvelope,
    SubmitAnswerCommand,
    SwapQuestionCommand,
    UseJokerCommand,
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = PROJECT_ROOT / "frontend" / "src" / "lib" / "protocol.generated.ts"


def _ts_type(schema: dict[str, Any]) -> str:
    if "const" in schema:
        return repr(schema["const"]).replace("'", '"')
    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "object":
        return "Record<string, unknown>"
    raise ValueError(f"unsupported protocol schema: {schema}")


def _interface(name: str, model: type[BaseModel]) -> str:
    schema = model.model_json_schema()
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field_name, field_schema in schema["properties"].items():
        optional = "" if field_name in required else "?"
        lines.append(f"  {field_name}{optional}: {_ts_type(field_schema)};")
    if name == "ServerEventEnvelope":
        lines.append("  [key: string]: unknown;")
    lines.append("}")
    return "\n".join(lines)


def generate_types() -> str:
    blocks = [
        "// Generated by backend/scripts/generate_protocol_types.py. Do not edit.",
        _interface("SubmitAnswerCommand", SubmitAnswerCommand),
        _interface("SwapQuestionCommand", SwapQuestionCommand),
        _interface("ExtendTimeCommand", ExtendTimeCommand),
        _interface("UseJokerCommand", UseJokerCommand),
        _interface("PingCommand", PingCommand),
        "export type ClientCommand = SubmitAnswerCommand | SwapQuestionCommand | ExtendTimeCommand | UseJokerCommand | PingCommand;",
        _interface("ServerEventEnvelope", ServerEventEnvelope),
    ]
    return "\n\n".join(blocks) + "\n"


def write_types() -> None:
    OUTPUT_PATH.write_text(generate_types(), encoding="utf-8")
