"""Source-audited Israeli and global pop-culture categories for batch V9.

``EXPANSION_V9`` adds verified density and genuine alternate names to the
eight new questions whose canonical cores live in :mod:`app.question_bank`.
English titles, official brand styles, former names, and established
abbreviations are aliases so one real-world entity cannot score twice.
"""

from __future__ import annotations

# answer tuples: (canonical, aliases, semantic_group | None)
EXPANSION_V9: dict[str, list[tuple[str, list[str], str | None]]] = {
    "כתבו שמות של סדרות טלוויזיה": [
        ("חברים", ["Friends"], None),
        ("משחקי הכס", ["Game of Thrones"], None),
        ("שובר שורות", ["Breaking Bad"], None),
        ("בית הנייר", ["Money Heist", "La Casa de Papel"], None),
        ("דברים מוזרים", ["Stranger Things"], None),
        ("הסימפסונים", ["The Simpsons"], None),
        ("סיינפלד", ["Seinfeld"], None),
        ("המשרד", ["The Office"], None),
        ("הסופרנוס", ["The Sopranos"], None),
        ("ריק ומורטי", ["Rick and Morty"], None),
        ("פאודה", ["Fauda"], None),
        ("שטיסל", ["Shtisel"], None),
        ("רמזור", ["Ramzor", "Traffic Light"], None),
        ("הפיג'מות", ["HaPijamot"], None),
        ("שמש", ["Shemesh"], None),
        ("זגורי אימפריה", ["Zaguri Imperia"], None),
        ("מטומטמת", ["Dumb"], None),
        ("המפקדת", ["Dismissed"], None),
        ("טהרן", ["Tehran"], None),
        ("חזרות", ["Rehearsals"], None),
        ("קופה ראשית", ["Checkout"], None),
        ("שרלוק", ["Sherlock"], None),
        ("דקסטר", ["Dexter"], None),
        ("סמוך על סול", ["Better Call Saul"], None),
    ],
    "כתבו שמות של שחקני כדורגל מפורסמים": [
        ("ליאונל מסי", ["Lionel Messi", "Messi"], None),
        ("כריסטיאנו רונאלדו", ["Cristiano Ronaldo", "CR7"], None),
        ("פלה", ["Pelé", "Edson Arantes do Nascimento"], None),
        ("דייגו מראדונה", ["Diego Maradona", "Maradona"], None),
        ("זינדין זידאן", ["Zinedine Zidane", "Zizou"], None),
        ("רונאלדיניו", ["Ronaldinho"], None),
        ("רונאלדו", ["Ronaldo Nazário", "R9"], None),
        ("יוהאן קרויף", ["Johan Cruyff"], None),
        ("פרנץ בקנבאואר", ["Franz Beckenbauer"], None),
        ("דייוויד בקהאם", ["David Beckham", "Beckham"], None),
        ("קיליאן אמבפה", ["Kylian Mbappé", "Mbappe"], None),
        ("ניימאר", ["Neymar", "Neymar Jr"], None),
        ("ארלינג הולאנד", ["Erling Haaland", "Haaland"], None),
        ("לוקה מודריץ'", ["Luka Modrić", "Modric"], None),
        ("מוחמד סלאח", ["Mohamed Salah", "Mo Salah"], None),
        ("רוברט לבנדובסקי", ["Robert Lewandowski", "Lewandowski"], None),
        ("כרים בנזמה", ["Karim Benzema", "Benzema"], None),
        ("תיירי הנרי", ["Thierry Henry"], None),
        ("אנדרס אינייסטה", ["Andrés Iniesta", "Iniesta"], None),
        ("צ'אבי", ["Xavi Hernández", "Xavi"], None),
        ("פאולו מלדיני", ["Paolo Maldini", "Maldini"], None),
        ("ג'אנלואיג'י בופון", ["Gianluigi Buffon", "Buffon"], None),
        ("יוסי בניון", ["Yossi Benayoun"], None),
        ("ערן זהבי", ["Eran Zahavi"], None),
    ],
    "כתבו שמות של קבוצות כדורגל": [
        ("ריאל מדריד", ["Real Madrid", "Real Madrid CF"], None),
        ("ברצלונה", ["FC Barcelona", "Barça"], None),
        ("ליברפול", ["Liverpool FC"], None),
        ("מנצ'סטר יונייטד", ["Manchester United", "Man United"], None),
        ("מנצ'סטר סיטי", ["Manchester City", "Man City"], None),
        ("ארסנל", ["Arsenal FC"], None),
        ("צ'לסי", ["Chelsea FC"], None),
        ("באיירן מינכן", ["FC Bayern München", "Bayern Munich"], None),
        ("יובנטוס", ["Juventus FC"], None),
        ("פריז סן ז'רמן", ["Paris Saint-Germain", "PSG"], None),
        ("מכבי תל אביב", ["Maccabi Tel Aviv FC"], None),
        ("מכבי חיפה", ["Maccabi Haifa FC"], None),
        ("הפועל תל אביב", ["Hapoel Tel Aviv FC"], None),
        ("הפועל באר שבע", ["Hapoel Beer-Sheva FC"], None),
        ("ביתר ירושלים", ["Beitar Jerusalem FC"], None),
        ("בורוסיה דורטמונד", ["Borussia Dortmund", "BVB"], None),
        ("אינטר", ["Inter Milan", "FC Internazionale Milano"], None),
        ("מילאן", ["AC Milan"], None),
        ("נאפולי", ["SSC Napoli"], None),
        ("אייאקס", ["AFC Ajax"], None),
        ("בנפיקה", ["SL Benfica"], None),
        ("אתלטיקו מדריד", ["Atlético de Madrid", "Atletico Madrid"], None),
        ("טוטנהאם", ["Tottenham Hotspur", "Spurs"], None),
    ],
    "כתבו שמות של רשתות מזון מהיר": [
        ("מקדונלד'ס", ["McDonald's"], None),
        ("בורגר קינג", ["Burger King"], None),
        ("קיי אף סי", ["KFC", "Kentucky Fried Chicken"], None),
        ("סאבוויי", ["Subway"], None),
        ("דומינוס", ["Domino's", "Domino's Pizza"], None),
        ("פיצה האט", ["Pizza Hut"], None),
        ("טאקו בל", ["Taco Bell"], None),
        ("ונדי'ס", ["Wendy's"], None),
        ("דאנקן", ["Dunkin'", "Dunkin' Donuts"], None),
        ("פופאי'ס", ["Popeyes", "Popeyes Louisiana Kitchen"], None),
        ("בורגראנץ'", ["Burgeranch"], None),
        ("פייב גאיז", ["Five Guys"], None),
        ("שייק שאק", ["Shake Shack"], None),
        ("צ'יק פילה", ["Chick-fil-A"], None),
        ("צ'יפוטלה", ["Chipotle", "Chipotle Mexican Grill"], None),
        ("ליטל סיזרס", ["Little Caesars"], None),
        ("פאפא ג'ונס", ["Papa Johns"], None),
        ("דיירי קווין", ["Dairy Queen", "DQ"], None),
        ("ארביס", ["Arby's"], None),
        ("סוניק", ["Sonic Drive-In"], None),
        ("ג'ק אין דה בוקס", ["Jack in the Box"], None),
        ("קארלס ג'וניור", ["Carl's Jr."], None),
        ("אין אנד אאוט", ["In-N-Out Burger", "In-N-Out"], None),
    ],
    "כתבו שמות של אפליקציות ורשתות חברתיות": [
        ("וואטסאפ", ["WhatsApp", "WhatsApp Messenger"], None),
        ("אינסטגרם", ["Instagram", "Insta"], None),
        ("פייסבוק", ["Facebook", "FB"], None),
        ("טיקטוק", ["TikTok"], None),
        ("יוטיוב", ["YouTube"], None),
        ("טלגרם", ["Telegram", "Telegram Messenger"], None),
        ("סנאפצ'ט", ["Snapchat", "Snap"], None),
        ("אקס", ["X", "Twitter", "טוויטר"], None),
        ("לינקדאין", ["LinkedIn"], None),
        ("רדיט", ["Reddit"], None),
        ("ספוטיפיי", ["Spotify"], None),
        ("ווייז", ["Waze"], None),
        ("גוגל מפות", ["Google Maps"], None),
        ("זום", ["Zoom", "Zoom Workplace"], None),
        ("דיסקורד", ["Discord"], None),
        ("טוויץ'", ["Twitch"], None),
        ("פינטרסט", ["Pinterest"], None),
        ("טינדר", ["Tinder"], None),
        ("ת'רדס", ["Threads", "Threads by Instagram"], None),
        ("סיגנל", ["Signal", "Signal Messenger"], None),
        ("גט", ["Gett"], None),
        ("מוביט", ["Moovit"], None),
    ],
    "כתבו שמות של מותגי אופנה וספורט": [
        ("נייקי", ["Nike"], None),
        ("אדידס", ["Adidas"], None),
        ("פומה", ["Puma"], None),
        ("ריבוק", ["Reebok"], None),
        ("אנדר ארמור", ["Under Armour"], None),
        ("ניו באלאנס", ["New Balance"], None),
        ("אסיקס", ["ASICS"], None),
        ("פילה", ["Fila"], None),
        ("קונברס", ["Converse"], None),
        ("ואנס", ["Vans"], None),
        ("זארה", ["Zara"], None),
        ("אייץ' אנד אם", ["H&M", "Hennes & Mauritz"], None),
        ("ליוויס", ["Levi's", "Levi Strauss"], None),
        ("גוצ'י", ["Gucci"], None),
        ("פראדה", ["Prada"], None),
        ("לואי ויטון", ["Louis Vuitton", "LV"], None),
        ("שאנל", ["Chanel"], None),
        ("דיור", ["Dior", "Christian Dior"], None),
        ("ארמני", ["Armani", "Giorgio Armani"], None),
        ("טומי הילפיגר", ["Tommy Hilfiger"], None),
        ("ראלף לורן", ["Ralph Lauren"], None),
        ("דה נורת' פייס", ["The North Face", "TNF"], None),
        ("קולומביה", ["Columbia Sportswear"], None),
        ("לולולמון", ["Lululemon"], None),
    ],
    "כתבו שמות של סרטי אקשן מפורסמים": [
        ("מת לחיות", ["Die Hard"], None),
        (
            "שליחות קטלנית 2",
            ["Terminator 2", "Terminator 2: Judgment Day", "T2"],
            None,
        ),
        ("מטריקס", ["The Matrix"], None),
        ("ג'ון וויק", ["John Wick"], None),
        ("מקס הזועם: כביש הזעם", ["Mad Max: Fury Road"], None),
        ("משימה בלתי אפשרית", ["Mission: Impossible"], None),
        ("שודדי התיבה האבודה", ["Raiders of the Lost Ark"], None),
        ("גלדיאטור", ["Gladiator"], None),
        ("אהבה בשחקים", ["Top Gun"], None),
        ("רמבו", ["First Blood", "Rambo: First Blood"], None),
        ("ספיד", ["Speed"], None),
        ("נשק קטלני", ["Lethal Weapon"], None),
        ("קיל ביל", ["Kill Bill", "Kill Bill: Volume 1"], None),
        ("האביר האפל", ["The Dark Knight"], None),
        ("קזינו רויאל", ["Casino Royale"], None),
        ("זהות כפולה", ["The Bourne Identity"], None),
        ("חטופה", ["Taken"], None),
        ("היט", ["Heat"], None),
        ("הפריצה לאלקטרז", ["The Rock"], None),
        ("עימות חזיתי", ["Face/Off"], None),
        ("הטורף", ["Predator"], None),
        ("קומנדו", ["Commando"], None),
        ("רובוקופ", ["RoboCop"], None),
    ],
    "כתבו שמות של חברות טכנולוגיה": [
        ("אפל", ["Apple", "Apple Inc."], None),
        ("מיקרוסופט", ["Microsoft"], None),
        ("גוגל", ["Google"], None),
        ("אמזון", ["Amazon"], None),
        ("מטא", ["Meta", "Meta Platforms"], None),
        ("סמסונג", ["Samsung", "Samsung Electronics"], None),
        ("אינטל", ["Intel"], None),
        ("אנבידיה", ["NVIDIA"], None),
        ("איי בי אם", ["IBM", "International Business Machines"], None),
        ("אורקל", ["Oracle", "Oracle Corporation"], None),
        ("סיסקו", ["Cisco", "Cisco Systems"], None),
        ("דל", ["Dell", "Dell Technologies"], None),
        ("אייץ' פי", ["HP", "Hewlett-Packard"], None),
        ("סוני", ["Sony"], None),
        ("אדובי", ["Adobe"], None),
        ("סיילספורס", ["Salesforce"], None),
        ("אס איי פי", ["SAP"], None),
        ("איי אמ די", ["AMD", "Advanced Micro Devices"], None),
        ("מובילאיי", ["Mobileye"], None),
        ("צ'ק פוינט", ["Check Point", "Check Point Software"], None),
        ("וויקס", ["Wix", "Wix.com"], None),
        ("מאנדיי", ["monday.com", "Monday"], None),
        ("פייבר", ["Fiverr"], None),
        ("נייס", ["NICE", "NICE Systems"], None),
    ],
}


CURATION_SOURCES: dict[str, list[str]] = {
    "כתבו שמות של סדרות טלוויזיה": [
        "https://www.imdb.com/chart/toptv/",
        "https://israelfilmacademy.co.il/media/2023/04/TVA_PROGRAM_ENG_V12.pdf",
        "https://www.kan.org.il/content/kan/kan-11/p-11766/",
        "https://www.netflix.com/title/80113612",
    ],
    "כתבו שמות של שחקני כדורגל מפורסמים": [
        "https://www.fifa.com/en/archive/ronaldo",
        "https://www.fifa.com/en/articles/pele-lionel-messi-goal-contributions-record",
        "https://www.football.org.il/national-team-game/?game_id=2641",
    ],
    "כתבו שמות של קבוצות כדורגל": [
        "https://www.uefa.com/uefachampionsleague/clubs/",
        "https://editorial.uefa.com/resources/029f-1f1d6ade076e-783243385d05-1000/uefa_european_football_directory_2025-26.pdf",
        "https://www.football.org.il/team-details/?team_id=2171",
    ],
    "כתבו שמות של רשתות מזון מהיר": [
        "https://www.fastfoodmarketing.org/media/2021-Fast-Food_FACTS_Ranking-v4%20FINAL.pdf",
        "https://industrygroup.org/wp-content/uploads/2025/10/QSR_2024_QSR50_REPORT-compressed.pdf",
        "https://app.burgeranch.co.il/en/",
    ],
    "כתבו שמות של אפליקציות ורשתות חברתיות": [
        "https://apps.apple.com/us/iphone/charts/6005",
        "https://play.google.com/store/apps",
        "https://www.appstoretracker.com/us/social-networking",
    ],
    "כתבו שמות של מותגי אופנה וספורט": [
        "https://fashionunited.com/i/most-valuable-fashion-brands",
        "https://www.sportvision.group/en/brands",
        "https://en-sa.sssports.com/brands",
    ],
    "כתבו שמות של סרטי אקשן מפורסמים": [
        "https://www.bfi.org.uk/lists/great-action-film-every-year-1924-now",
        "https://www.bfi.org.uk/lists/10-great-action-movies",
        "https://editorial.rottentomatoes.com/guide/140-essential-action-movies-to-watch-now/",
    ],
    "כתבו שמות של חברות טכנולוגיה": [
        "https://fortune.com/ranking/fortune500--technology/2024/",
        "https://brandirectory.com/reports/technology/2026",
        "https://documents.worldbank.org/curated/en/526981530526619514/pdf/Best-Practices-and-Lessons-Learned-in-ICT-Sector-Innovation-A-Case-Study-of-Israel.pdf",
    ],
}
