"""Source-audited fun-category expansion for batch V6.

``EXPANSION_V6`` adds real canonicals and useful alternate names to the ten
new questions whose generous answer cores live in :mod:`app.question_bank`.
Aliases are genuine English names, stage names, identities, abbreviations, or
common alternate titles; normalization-only Hebrew variants are omitted.
"""

from __future__ import annotations

# answer tuples: (canonical, aliases, semantic_group | None)
EXPANSION_V6: dict[str, list[tuple[str, list[str], str | None]]] = {
    "כתבו שמות של זמרים וזמרות ישראלים": [
        ("נינט טייב", ["נינט", "Ninet Tayeb"], None),
        ("הראל סקעת", ["Harel Skaat"], None),
        ("שירי מימון", ["Shiri Maimon"], None),
        ("עידן רייכל", ["Idan Raichel"], None),
        ("עידן עמדי", ["Idan Amedi"], None),
        ("רביב כנר", ["Raviv Kaner"], None),
        ("אודיה", ["אודיה אזולאי", "Odeya"], None),
        ("יובל דיין", ["Yuval Dayan"], None),
        ("מארינה מקסימיליאן", ["מרינה מקסימיליאן בלומין"], None),
        ("דיקלה", ["דיקלה דורי", "Dikla"], None),
        ("אביתר בנאי", ["Eviatar Banai"], None),
        ("מאיר בנאי", ["Meir Banai"], None),
        ("אהוד בנאי", ["Ehud Banai"], None),
        ("יוני בלוך", ["Yoni Bloch"], None),
        ("דוד ברוזה", ["David Broza"], None),
        ("מאיר אריאל", ["Meir Ariel"], None),
        ("אריאל זילבר", ["Ariel Zilber"], None),
        ("קורין אלאל", ["Corinne Allal"], None),
        ("דנה אינטרנשיונל", ["Dana International", "שרון כהן"], None),
        ("יזהר כהן", ["Izhar Cohen"], None),
        ("סטטיק", ["לירז רוסו", "Static"], None),
        ("בן אל תבורי", ["Ben El Tavori"], None),
        ("משינה", ["Mashina"], None),
        ("הדג נחש", ["Hadag Nahash"], None),
        ("התקווה 6", ["Hatikva 6"], None),
    ],
    "כתבו שמות של מאכלים ישראליים": [
        ("ירקות כבושים", ["חמוצים"], None),
        ("עמבה", ["Amba"], None),
        ("סחוג", ["זחוק", "Zhug"], None),
        ("לבנה", ["Labneh"], None),
        ("מלבי", ["Muhallebi"], None),
        ("כנאפה", ["Knafeh"], None),
        ("חלבה", ["Halva"], None),
        ("סופגנייה", ["Sufganiyah"], None),
        ("אוזן המן", ["Hamantaschen"], None),
        ("רוגלך", ["Rugelach"], None),
        ("בייגלה ירושלמי", ["Jerusalem bagel"], None),
        ("קובנה", ["Kubaneh"], None),
        ("פריקסה", ["Fricassé", "Fricasse"], None),
        ("מוסקה", ["Moussaka"], None),
        ("מקלובה", ["Maqluba"], None),
        ("עלי גפן ממולאים", ["דולמה"], None),
        ("מרק עדשים", [], None),
        ("מרק קובה", [], "kuba"),
        ("קובה סלק", ["קובה אדומה"], "kuba"),
        ("קבב", ["Kebab"], None),
        ("דג מרוקאי", [], None),
        ("מופלטה", ["Moufleta"], None),
        ("סמבוסק", ["Sambusak"], None),
        ("מעמול", ["Ma'amoul", "Maamoul"], None),
        ("עוגת שמרים", [], None),
    ],
    "כתבו שמות של חיות משק וחווה": [
        ("תאו מים", ["Water buffalo"], None),
        ("פרד", ["Mule"], None),
        ("גמל", ["Camel"], None),
        ("למה", ["Llama"], None),
        ("אלפקה", ["Alpaca"], None),
        ("יאק", ["Yak"], None),
        ("פנינייה", ["Guinea fowl"], None),
        ("שליו", ["Quail"], None),
        ("יונה", ["Domestic pigeon"], None),
        ("טווס", ["Peafowl"], None),
        ("יען", ["Ostrich"], None),
        ("אמו", ["Emu"], None),
        ("אייל", ["Deer"], None),
        ("אייל צפוני", ["Reindeer"], None),
        ("פסיון", ["Pheasant"], None),
        ("מינק", ["Mink"], None),
        ("צ'ינצ'ילה", ["Chinchilla"], None),
        ("שרקן", ["Guinea pig"], None),
        ("קרפיון", ["Carp"], None),
        ("אמנון", ["Tilapia"], None),
    ],
    "כתבו שמות של סרטים של דיסני ופיקסאר": [
        ("101 כלבים דלמטיים", ["One Hundred and One Dalmatians", "101 Dalmatians"], None),
        ("עליסה בארץ הפלאות", ["Alice in Wonderland"], None),
        ("היפהפייה הנרדמת", ["Sleeping Beauty"], None),
        ("הגיבן מנוטרדאם", ["The Hunchback of Notre Dame"], None),
        ("פוקהונטס", ["Pocahontas"], None),
        ("הקיסר נפל על הראש", ["The Emperor's New Groove"], None),
        ("אטלנטיס האימפריה האבודה", ["Atlantis: The Lost Empire"], None),
        ("כוכב המטמון", ["Treasure Planet"], None),
        ("בולט", ["Bolt"], None),
        ("הנסיכה והצפרדע", ["The Princess and the Frog"], None),
        ("פו הדב", ["Winnie the Pooh"], None),
        ("ריה והדרקון האחרון", ["Raya and the Last Dragon"], None),
        ("עולם מוזר", ["Strange World"], None),
        ("המשאלה", ["Wish"], None),
        ("באג לייף", ["A Bug's Life", "A Bugs Life"], None),
        ("צעצוע של סיפור 2", ["Toy Story 2"], None),
        ("צעצוע של סיפור 3", ["Toy Story 3"], None),
        ("מוצאים את דורי", ["Finding Dory"], None),
        ("בית ספר למפלצות", ["Monsters University"], None),
        ("הדינוזאור הטוב", ["The Good Dinosaur"], None),
        ("קדימה", ["Onward"], None),
        ("אדומה אש", ["Turning Red"], None),
        ("שנות אור", ["Lightyear"], None),
        ("אלמנטלי", ["Elemental"], None),
        ("הקול בראש 2", ["Inside Out 2"], None),
    ],
    "כתבו שמות של מותגי חטיפים ושוקולד": [
        ("באונטי", ["Bounty"], None),
        ("קראנץ'", ["Crunch"], None),
        ("ליון", ["Lion"], None),
        ("איירו", ["Aero"], None),
        ("קדבורי", ["Cadbury"], None),
        ("לינדט", ["Lindt"], None),
        ("גודייבה", ["Godiva"], None),
        ("ריטר ספורט", ["Ritter Sport"], None),
        ("מרסי", ["Merci"], None),
        ("ריסז", ["Reese's", "Reeses"], None),
        ("סקיטלס", ["Skittles"], None),
        ("מלטיזרס", ["Maltesers"], None),
        ("מנצ'יז", ["Munchies"], None),
        ("טוויסט", [], None),
        ("פסק זמן רול", [], "pesek-zman"),
        ("פסק זמן ביג בייט", [], "pesek-zman"),
        ("במבה נוגט", ["במבה במילוי נוגט"], "bamba"),
        ("במבה אדומה", [], "bamba"),
        ("ביסלי גריל", [], "bissli"),
        ("ביסלי פלאפל", [], "bissli"),
        ("תפוצ'יפס קראנצ'", [], "tapuchips"),
        ("פופקורן הוט פופ", ["Hot Pop"], None),
        ("קליק ביסקוויט", [], "click"),
        ("קינדר בואנו", ["Kinder Bueno"], "kinder"),
        ("קינדר אצבעות", ["Kinder Chocolate"], "kinder"),
    ],
    "כתבו שמות של משחקי מחשב ווידאו": [
        ("גנסין אימפקט", ["Genshin Impact"], None),
        ("פול גייז", ["Fall Guys"], None),
        ("קלאש אוף קלאנס", ["Clash of Clans", "COC"], None),
        ("קלאש רויאל", ["Clash Royale"], None),
        ("ברול סטארס", ["Brawl Stars"], None),
        ("קנדי קראש", ["Candy Crush", "Candy Crush Saga"], None),
        ("אנגרי בירדס", ["Angry Birds"], None),
        ("פלנטס נגד זומבים", ["Plants vs. Zombies", "Plants vs Zombies"], None),
        ("פורטאל", ["Portal"], None),
        ("האף לייף", ["Half-Life", "Half Life"], None),
        ("ביושוק", ["BioShock"], None),
        ("פולאאוט", ["Fallout"], None),
        ("מס אפקט", ["Mass Effect"], None),
        ("הוויצ'ר", ["The Witcher", "Witcher"], None),
        ("אלדן רינג", ["Elden Ring"], None),
        ("דארק סולס", ["Dark Souls"], None),
        ("סקירו", ["Sekiro: Shadows Die Twice", "Sekiro"], None),
        ("סייברפאנק 2077", ["Cyberpunk 2077"], None),
        ("דום", ["Doom"], None),
        ("קווייק", ["Quake"], None),
        ("סטארקראפט", ["StarCraft"], None),
        ("אייג' אוף אמפיירס", ["Age of Empires", "AOE"], None),
        ("סיוויליזציה", ["Civilization", "Sid Meier's Civilization"], None),
        ("סימסיטי", ["SimCity"], None),
        ("הירוס 3", ["Heroes of Might and Magic III", "Heroes 3"], None),
    ],
    "כתבו שמות של גיבורי על": [
        ("מיס מארוול", ["Ms. Marvel", "Ms Marvel", "קמלה חאן"], None),
        ("שי האלק", ["She-Hulk", "She Hulk", "ג'ניפר וולטרס"], None),
        ("מון נייט", ["Moon Knight", "מארק ספקטור"], None),
        ("בלייד", ["Blade"], None),
        ("גוסט ריידר", ["Ghost Rider"], None),
        ("סטאר לורד", ["Star-Lord", "Star Lord", "פיטר קוויל"], None),
        ("סייקלופס", ["Cyclops", "סקוט סאמרס"], None),
        ("סטורם", ["Storm", "אורורו מונרו"], None),
        ("פרופסור אקס", ["Professor X", "צ'ארלס אקסבייר"], None),
        ("ג'ין גריי", ["Jean Grey", "פניקס"], None),
        ("אייסמן", ["Iceman", "בובי דרייק"], None),
        ("ביסט", ["Beast", "האנק מקוי"], None),
        ("האלק", ["הענק הירוק"], "hulk"),
        ("ספיידר גוון", ["Spider-Gwen", "Ghost-Spider", "גוון סטייסי"], None),
        ("מיילס מוראלס", ["Miles Morales", "ספיידרמן מיילס"], None),
        ("הלבוי", ["Hellboy"], None),
        ("צבי הנינג'ה", ["Teenage Mutant Ninja Turtles", "TMNT"], None),
        ("הנוקמים", ["Avengers", "האוונג'רס"], None),
        ("אקס מן", ["X-Men", "X Men"], None),
        ("ליגת הצדק", ["Justice League"], None),
        ("ארבעת המופלאים", ["Fantastic Four"], None),
        ("שומרי הגלקסיה", ["Guardians of the Galaxy"], None),
    ],
    "כתבו שמות של דמויות מצוירות מפורסמות": [
        ("צ'רלי בראון", ["Charlie Brown"], None),
        ("טוויטי", ["Tweety"], None),
        ("סילבסטר", ["Sylvester the Cat", "Sylvester"], None),
        ("רוד ראנר", ["Road Runner"], None),
        ("וייל אי קויוטי", ["Wile E. Coyote", "Wile E Coyote"], None),
        ("הפנתר הוורוד", ["Pink Panther"], None),
        ("וודי", ["Woody"], None),
        ("באז שנות אור", ["Buzz Lightyear"], None),
        ("מייק ווזאוסקי", ["Mike Wazowski", "מייק"], None),
        ("סאלי", ["James P. Sullivan", "Sulley"], None),
        ("פו הדב", ["Winnie the Pooh", "Winnie-the-Pooh"], None),
        ("טיגר", ["Tigger"], None),
        ("איה", ["Eeyore"], None),
        ("מוגלי", ["Mowgli"], None),
        ("באלו", ["Baloo"], None),
        ("אלאדין", ["Aladdin"], None),
        ("ג'יני", ["Genie"], None),
        ("מולאן", ["Mulan"], None),
        ("פו", ["Po", "קונג פו פנדה"], None),
        ("הדרדסבא", ["Papa Smurf"], None),
        ("גרגמל", ["Gargamel"], None),
        ("בן 10", ["Ben 10", "בן טניסון"], None),
        ("קים פוסיבול", ["Kim Possible"], None),
        ("פיניאס", ["Phineas Flynn", "Phineas"], None),
        ("פרב", ["Ferb Fletcher", "Ferb"], None),
    ],
    "כתבו שמות של סוגי ממתקים": [
        ("טאפי", ["Taffy"], None),
        ("גאמדראפ", ["Gumdrop"], None),
        ("פסטיל", ["Pastille"], None),
        ("סוכר גבישי", ["Rock candy"], None),
        ("טופי כוורת", ["Honeycomb toffee"], None),
        ("בוטנים מסוכרים", ["Candied peanuts"], None),
        ("צימוקים מצופים שוקולד", ["Chocolate-covered raisins"], None),
        ("בייגלה מצופה שוקולד", ["Chocolate-covered pretzel"], None),
        ("תות מצופה שוקולד", ["Chocolate-covered strawberry"], None),
        ("דובוני גומי", ["Gummy bears"], "gummy"),
        ("תולעי גומי", ["Gummy worms"], "gummy"),
        ("חגורות גומי", ["Gummy belts", "חגורות חמוצות"], "gummy"),
        ("עדשי שוקולד", ["Chocolate lentils"], None),
        ("ביצה משוקולד", ["Chocolate egg"], None),
        ("לבבות שוקולד", ["Chocolate hearts"], None),
        ("סוכריות דבש", ["Honey candy"], None),
        ("סוכריות קפה", ["Coffee candy"], None),
        ("סוכריות חמאה", ["Butterscotch"], None),
        ("פונדנט", ["Fondant candy"], None),
        ("מקרון קוקוס", ["Coconut macaroon"], None),
        ("קוקוס ורוד", ["Coconut ice"], None),
        ("שוקולד ממולא ליקר", ["Liqueur chocolate"], None),
    ],
    "כתבו דברים שמוצאים במטבח": [
        ("מעבד מזון", ["פוד פרוססור", "Food processor"], None),
        ("טוסטר אובן", ["Toaster oven"], None),
        ("מכונת קפה", ["Coffee machine"], None),
        ("מטחנת קפה", [], None),
        ("סיר לחץ", [], None),
        ("סיר בישול איטי", ["Slow cooker"], None),
        ("ווק", ["Wok"], None),
        ("אייר פרייר", ["טיגון באוויר", "Air fryer"], None),
        ("מועך תפוחי אדמה", ["מועך פירה"], None),
        ("כותש שום", ["מועך שום"], None),
        ("מלקחיים", ["מלקחי מטבח"], None),
        ("מספרי מטבח", ["מספריים למטבח"], None),
        ("כף עץ", [], None),
        ("כף מחוררת", [], None),
        ("קופסת אחסון", ["קופסת אוכל"], None),
        ("צנצנת", [], None),
        ("בקבוק", [], None),
        ("ניילון נצמד", [], None),
        ("נייר אלומיניום", ["רדיד אלומיניום"], None),
        ("שקית אשפה", [], None),
        ("פח אשפה", ["פח"], None),
        ("סבון כלים", [], None),
        ("ספוג כלים", ["סקוץ'"], None),
        ("מתקן ייבוש כלים", ["מייבש כלים"], None),
        ("מדף תבלינים", [], None),
        ("מלחייה", [], None),
        ("פלפלייה", [], None),
        ("קערת ערבוב", [], None),
        ("כוס מדידה", [], None),
        ("משקל מטבח", [], None),
    ],
}


# Boundary policies required by docs/ADDING_A_QUESTION.md for new questions.
QUESTION_POLICIES_V6: dict[str, dict[str, str | list[str]]] = {
    "כתבו שמות של זמרים וזמרות ישראלים": {
        "includes": "Real Israeli solo singers, singer-songwriters, duos, and vocal bands.",
        "excludes": ["שיר", "אלבום", "זמר שאינו ישראלי"],
        "granularity": "Each performer or established group scores once; stage names are aliases.",
        "time_and_place": "Israeli popular music across historical and current eras.",
        "brands": "Not applicable.",
        "language": "Common Hebrew names, real stage names, and established English forms.",
    },
    "כתבו שמות של מאכלים ישראליים": {
        "includes": "Dishes, breads, condiments, and sweets established in Israeli food culture.",
        "excludes": ["חומר גלם לבדו", "שם מסעדה", "מנה שאין לה זיקה למטבח בישראל"],
        "granularity": "Recognizable dishes and established variants may score separately.",
        "time_and_place": "The multicultural Israeli kitchen, including its Jewish and regional roots.",
        "brands": "Food brands do not score unless the name also denotes the established food.",
        "language": "Common Hebrew names and established source-language or English names.",
    },
    "כתבו שמות של חיות משק וחווה": {
        "includes": "Domesticated livestock, poultry, working, companion, and farmed animals.",
        "excludes": ["חיית בר שאינה מגודלת בחווה", "גזע כאילו הוא מין חדש", "צעצוע חיה"],
        "granularity": "Species and familiar age or sex labels are accepted; same-species labels share scoring groups where appropriate.",
        "time_and_place": "Common farm animals worldwide.",
        "brands": "Not applicable.",
        "language": "Common Hebrew animal names and established English names.",
    },
    "כתבו שמות של סרטים של דיסני ופיקסאר": {
        "includes": "Feature films released under Disney animation or Pixar, including sequels.",
        "excludes": ["דמות בלבד", "סדרת טלוויזיה בלבד", "סרט מאולפן שאינו דיסני או פיקסאר"],
        "granularity": "Each feature title and numbered sequel can score separately.",
        "time_and_place": "Released Disney and Pixar feature films across all eras.",
        "brands": "Disney and Pixar are the defining studio brands for this question.",
        "language": "Israeli Hebrew titles, original English titles, and established colloquial titles.",
    },
    "כתבו שמות של מותגי חטיפים ושוקולד": {
        "includes": "Real snack, chocolate, wafer, cookie, and confectionery brands or named product lines.",
        "excludes": ["טעם בלבד", "יצרן שאינו מותג מזון", "שם מומצא"],
        "granularity": "A parent brand and well-known named product lines may score separately; variants share groups where needed.",
        "time_and_place": "Brands commonly sold in Israel, including international brands.",
        "brands": "Commercial brands and named branded products are intentionally accepted.",
        "language": "Hebrew market names and official Latin-script brand names.",
    },
    "כתבו שמות של משחקי מחשב ווידאו": {
        "includes": "Real computer, console, arcade, browser, and mobile video-game titles or franchises.",
        "excludes": ["משחק קופסה בלבד", "קונסולה", "חברת משחקים בלי משחק בשם זה"],
        "granularity": "A franchise can score under its common title; distinctive games and sequels may score separately.",
        "time_and_place": "International video games from classic arcade titles through current games.",
        "brands": "Game franchise names are accepted; hardware brands alone are not.",
        "language": "Common Hebrew transliterations, official English titles, and established abbreviations.",
    },
    "כתבו שמות של גיבורי על": {
        "includes": "Named superheroes, established heroic antiheroes, and famous superhero teams.",
        "excludes": ["נבל בלבד", "שחקן שמגלם גיבור", "כוח על בלי שם דמות"],
        "granularity": "A hero and their civilian identity score once; distinct mantle holders may be separate when commonly named.",
        "time_and_place": "Major international comics, animation, television, and film continuities.",
        "brands": "Marvel, DC, and other publishers are allowed; publisher names alone do not score.",
        "language": "Common Hebrew names, official English names, civilian identities, and established translations.",
    },
    "כתבו שמות של דמויות מצוירות מפורסמות": {
        "includes": "Named characters famous from animation, animated films, anime, or cartoons.",
        "excludes": ["שם סדרה בלי דמות בשם זה", "שחקן דיבוב", "דמות לייב אקשן בלבד"],
        "granularity": "Each named character scores once; nicknames and original-language names are aliases.",
        "time_and_place": "International family and adult animation across eras.",
        "brands": "Characters from any real animation studio or franchise are accepted.",
        "language": "Common Hebrew names and official English or original names.",
    },
    "כתבו שמות של סוגי ממתקים": {
        "includes": "Recognized sugar confectionery, chocolate confections, chewing gum, and named candy forms.",
        "excludes": ["עוגה", "משקה מתוק", "מותג בלי ציון סוג ממתק"],
        "granularity": "Broad candy families and recognizable forms may score separately.",
        "time_and_place": "International confectionery types, historical and current.",
        "brands": "Generic candy types score; brand-only answers belong in the brand question.",
        "language": "Common Hebrew names and established English confectionery terms.",
    },
    "כתבו דברים שמוצאים במטבח": {
        "includes": "Kitchen utensils, cookware, appliances, furniture, storage, and cleaning items normally found in a kitchen.",
        "excludes": ["חפץ שאין לו שימוש ביתי במטבח", "חדר בבית", "מותג בלי ציון חפץ"],
        "granularity": "Broad objects and distinct common subtypes can score separately.",
        "time_and_place": "Contemporary home kitchens, with common traditional utensils also accepted.",
        "brands": "Generic object names score; a brand may be an alias only when commonly used for that object.",
        "language": "Common Hebrew names and established English appliance or utensil names.",
    },
}


CURATION_SOURCES: dict[str, list[str]] = {
    "כתבו שמות של זמרים וזמרות ישראלים": [
        "https://acum.org.il/",
        "https://www.kan.org.il/content/archive1/archivemusic/",
    ],
    "כתבו שמות של מאכלים ישראליים": [
        "https://www.nli.org.il/en/discover/israel-culture-and-society/israeli-food/israeli-kitchen",
        "https://www.gov.il/BlobFolder/generalpage/facts-about-israel-2018/en/English_ABOUT_ISRAEL_PDF_Israel%20Lifestyle%202018.pdf",
        "https://en.wikipedia.org/wiki/List_of_Israeli_dishes",
    ],
    "כתבו שמות של חיות משק וחווה": [
        "https://agrovoc.fao.org/browse/agrovoc/en/page/c_4397",
        "https://www.fao.org/livestock-systems/en/",
        "https://www.fao.org/dad-is/en",
    ],
    "כתבו שמות של סרטים של דיסני ופיקסאר": [
        "https://disneyanimation.com/films/",
        "https://www.pixar.com/feature-films/",
        "https://movies.disney.com/a-z",
    ],
    "כתבו שמות של מותגי חטיפים ושוקולד": [
        "https://www.osem-nestle.co.il/brands",
        "https://www.strauss-group.com/brands/",
        "https://www.ferrero.com/int/en/our-brands",
    ],
    "כתבו שמות של משחקי מחשב ווידאו": [
        "https://www.esrb.org/search/",
        "https://www.mobygames.com/game/",
    ],
    "כתבו שמות של גיבורי על": [
        "https://www.marvel.com/characters",
        "https://www.dc.com/characters",
    ],
    "כתבו שמות של דמויות מצוירות מפורסמות": [
        "https://mickey.disney.com/",
        "https://www.warnerbros.com/brands/looney-tunes",
        "https://www.nick.com/shows/spongebob-squarepants",
    ],
    "כתבו שמות של סוגי ממתקים": [
        "https://www.britannica.com/topic/candy-food",
        "https://en.wikipedia.org/wiki/List_of_candies",
        "https://en.wikipedia.org/wiki/Sugar_candy",
    ],
    "כתבו דברים שמוצאים במטבח": [
        "https://www.fda.gov/food/buy-store-serve-safe-food/safe-food-handling",
        "https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics",
        "https://www.osha.gov/etools/hospitals/food-services/kitchen-equipment",
    ],
}
