"""Closed-set questions and source-audited existing-category curation.

This batch favors finite categories with stable membership.  Aliases are real
alternate names, established English forms, symbols, or common abbreviations;
normalization-only Hebrew spelling variants are deliberately omitted.
"""

from __future__ import annotations

# answer tuples: (canonical, aliases, semantic_group | None)
QUESTION_EXPANSIONS_V4: dict[str, list[tuple[str, list[str], str | None]]] = {
    "כתבו שמות של מדינות באסיה": [
        ("כווית", ["Kuwait"], None),
        ("קפריסין", ["Cyprus"], None),
    ],
    "כתבו שמות של ערי בירה בעולם": [
        ("גיטגה", ["Gitega"], None),
        ("פורטו נובו", ["Porto-Novo"], None),
        ("ואגאדוגו", ["Ouagadougou"], None),
        ("פראיה", ["Praia"], None),
        ("בנגי", ["Bangui"], None),
        ("נג'מנה", ["N'Djamena"], None),
        ("מורוני", ["Moroni"], None),
        ("ג'יבוטי", ["Djibouti"], None),
        ("מלאבו", ["Malabo"], None),
        ("אסמרה", ["Asmara"], None),
        ("ליברוויל", ["Libreville"], None),
        ("קונאקרי", ["Conakry"], None),
        ("ביסאו", ["Bissau"], None),
        ("בנז'ול", ["Banjul"], None),
        ("מסרו", ["Maseru"], None),
        ("אנטננריבו", ["Antananarivo"], None),
        ("לילונגווה", ["Lilongwe"], None),
        ("מונרוביה", ["Monrovia"], None),
        ("פורט לואי", ["Port Louis"], None),
        ("נואקשוט", ["Nouakchott"], None),
        ("ניאמיי", ["Niamey"], None),
        ("יאמוסוקרו", ["Yamoussoukro"], None),
        ("סאו טומה", ["São Tomé", "Sao Tome"], None),
        ("פריטאון", ["Freetown"], None),
        ("מוגדישו", ["Mogadishu"], None),
        ("ג'ובה", ["Juba"], None),
        ("לומה", ["Lomé", "Lome"], None),
    ],
}


ANSWER_ALIAS_ADDITIONS_V4: dict[str, dict[str, list[str]]] = {
    "כתבו שמות של מדינות בארצות הברית": {
        "אלבמה": ["Alabama", "AL"],
        "אלסקה": ["Alaska", "AK"],
        "אריזונה": ["Arizona", "AZ"],
        "ארקנסו": ["Arkansas", "AR"],
        "קליפורניה": ["California", "CA"],
        "קולורדו": ["Colorado", "CO"],
        "קונטיקט": ["Connecticut", "CT"],
        "דלאוור": ["Delaware", "DE"],
        "פלורידה": ["Florida", "FL"],
        "ג'ורג'יה": ["Georgia", "GA"],
        "הוואי": ["Hawaii", "HI"],
        "איידהו": ["Idaho", "ID"],
        "אילינוי": ["Illinois", "IL"],
        "אינדיאנה": ["Indiana", "IN"],
        "איווה": ["Iowa", "IA"],
        "קנזס": ["Kansas", "KS"],
        "קנטקי": ["Kentucky", "KY"],
        "לואיזיאנה": ["Louisiana", "LA"],
        "מיין": ["Maine", "ME"],
        "מרילנד": ["Maryland", "MD"],
        "מסצ'וסטס": ["Massachusetts", "MA"],
        "מישיגן": ["Michigan", "MI"],
        "מינסוטה": ["Minnesota", "MN"],
        "מיסיסיפי": ["Mississippi", "MS"],
        "מיזורי": ["Missouri", "MO"],
        "מונטנה": ["Montana", "MT"],
        "נברסקה": ["Nebraska", "NE"],
        "נבדה": ["Nevada", "NV"],
        "ניו המפשייר": ["New Hampshire", "NH"],
        "ניו ג'רזי": ["New Jersey", "NJ"],
        "ניו מקסיקו": ["New Mexico", "NM"],
        "ניו יורק": ["New York", "NY"],
        "קרוליינה הצפונית": ["North Carolina", "NC"],
        "דקוטה הצפונית": ["North Dakota", "ND"],
        "אוהיו": ["Ohio", "OH"],
        "אוקלהומה": ["Oklahoma", "OK"],
        "אורגון": ["Oregon", "OR"],
        "פנסילבניה": ["Pennsylvania", "PA"],
        "רוד איילנד": ["Rhode Island", "RI"],
        "קרוליינה הדרומית": ["South Carolina", "SC"],
        "דקוטה הדרומית": ["South Dakota", "SD"],
        "טנסי": ["Tennessee", "TN"],
        "טקסס": ["Texas", "TX"],
        "יוטה": ["Utah", "UT"],
        "ורמונט": ["Vermont", "VT"],
        "וירג'יניה": ["Virginia", "VA"],
        "וושינגטון": ["Washington", "WA"],
        "וירג'יניה המערבית": ["West Virginia", "WV"],
        "ויסקונסין": ["Wisconsin", "WI"],
        "ויומינג": ["Wyoming", "WY"],
    },
    "כתבו שמות של מדינות באפריקה": {
        "אלג'יריה": ["Algeria"],
        "אנגולה": ["Angola"],
        "בנין": ["Benin"],
        "בוצוואנה": ["Botswana", "בוטסואנה", "בוטסוואנה"],
        "בורקינה פאסו": ["Burkina Faso"],
        "בורונדי": ["Burundi"],
        "כף ורדה": ["Cabo Verde", "Cape Verde", "קאבו ורדה"],
        "קמרון": ["Cameroon"],
        "הרפובליקה המרכז-אפריקאית": [
            "Central African Republic",
            "CAR",
            "רפובליקת מרכז אפריקה",
        ],
        "צ'אד": ["Chad"],
        "קומורו": ["Comoros", "איי קומורו"],
        "הרפובליקה הדמוקרטית של קונגו": [
            "Democratic Republic of the Congo",
            "DR Congo",
            "DRC",
            "Congo-Kinshasa",
            "קונגו קינשאסה",
        ],
        "הרפובליקה של קונגו": [
            "Republic of the Congo",
            "Congo-Brazzaville",
            "קונגו ברזוויל",
        ],
        "חוף השנהב": ["Côte d'Ivoire", "Cote d'Ivoire", "Ivory Coast"],
        "ג'יבוטי": ["Djibouti"],
        "מצרים": ["Egypt"],
        "גינאה המשוונית": ["Equatorial Guinea"],
        "אריתריאה": ["Eritrea"],
        "אסוואטיני": ["Eswatini", "Swaziland", "סווזילנד"],
        "אתיופיה": ["Ethiopia"],
        "גבון": ["Gabon"],
        "גמביה": ["Gambia", "The Gambia"],
        "גאנה": ["Ghana"],
        "גינאה": ["Guinea"],
        "גינאה ביסאו": ["Guinea-Bissau"],
        "קניה": ["Kenya"],
        "לסוטו": ["Lesotho"],
        "ליבריה": ["Liberia"],
        "לוב": ["Libya"],
        "מדגסקר": ["Madagascar"],
        "מלאווי": ["Malawi"],
        "מאלי": ["Mali"],
        "מאוריטניה": ["Mauritania"],
        "מאוריציוס": ["Mauritius"],
        "מרוקו": ["Morocco"],
        "מוזמביק": ["Mozambique"],
        "נמיביה": ["Namibia"],
        "ניז'ר": ["Niger"],
        "ניגריה": ["Nigeria"],
        "רואנדה": ["Rwanda"],
        "סאו טומה ופרינסיפה": ["Sao Tome and Principe", "São Tomé and Príncipe"],
        "סנגל": ["Senegal"],
        "סיישל": ["Seychelles"],
        "סיירה לאון": ["Sierra Leone"],
        "סומליה": ["Somalia"],
        "דרום אפריקה": ["South Africa"],
        "דרום סודאן": ["South Sudan"],
        "סודאן": ["Sudan"],
        "טנזניה": ["Tanzania", "United Republic of Tanzania"],
        "טוגו": ["Togo"],
        "תוניסיה": ["Tunisia"],
        "אוגנדה": ["Uganda"],
        "זמביה": ["Zambia"],
        "זימבבואה": ["Zimbabwe"],
    },
    "כתבו שמות של מדינות באסיה": {
        "איחוד האמירויות": ["United Arab Emirates"],
        "דרום קוריאה": ["South Korea", "Republic of Korea", "ROK"],
        "צפון קוריאה": ["North Korea", "DPRK"],
        "מזרח טימור": ["East Timor", "Timor-Leste"],
        "מיאנמר": ["Myanmar", "Burma"],
        "האיים המלדיביים": ["Maldives"],
        "סרי לנקה": ["Sri Lanka"],
        "טייוואן": ["Taiwan"],
    },
    "כתבו שמות של גרמי שמיים במערכת השמש": {
        "השמש": ["Sun"],
        "כוכב חמה": ["Mercury"],
        "נוגה": ["Venus"],
        "כדור הארץ": ["Earth"],
        "מאדים": ["Mars"],
        "צדק": ["Jupiter"],
        "שבתאי": ["Saturn"],
        "אורנוס": ["Uranus"],
        "נפטון": ["Neptune"],
        "פלוטו": ["Pluto"],
        "הירח": ["Moon", "Luna"],
        "אירופה": ["Europa"],
        "טיטאן": ["Titan"],
        "גנימד": ["Ganymede"],
        "איו": ["Io"],
        "קליסטו": ["Callisto"],
        "קרס": ["Ceres"],
        "אריס": ["Eris"],
    },
}


ANSWER_GROUP_UPDATES_V4: dict[str, dict[str, str]] = {}


# Boundary policies required by docs/ADDING_A_QUESTION.md for new questions.
QUESTION_POLICIES_V4: dict[str, dict[str, str | list[str]]] = {
    "כתבו שמות של מדינות בארצות הברית": {
        "includes": "The 50 states of the United States.",
        "excludes": ["מחוז קולומביה", "פוארטו ריקו", "גואם"],
        "granularity": "States only; cities, counties, districts, and territories do not score.",
        "time_and_place": "The current federal set of 50 U.S. states.",
        "brands": "Not applicable.",
        "language": "Hebrew and English state names plus official USPS abbreviations.",
    },
    "כתבו שמות של מדינות באפריקה": {
        "includes": "UN member states assigned to Africa by the UN M49 geography.",
        "excludes": ["סהרה המערבית", "ראוניון", "מיוט"],
        "granularity": "Sovereign UN member states only; dependencies do not score.",
        "time_and_place": "Current UN membership and M49 continental classification.",
        "brands": "Not applicable.",
        "language": "Hebrew and English short names plus established former or formal names.",
    },
}


QUESTION_EXPANSION_SOURCES_V4: dict[str, list[str]] = {
    "כתבו שמות של מדינות בארצות הברית": [
        "https://www.census.gov/library/reference/code-lists/ansi/ansi-codes-for-states.html",
        "https://about.usps.com/who/profile/history/state-abbreviations.htm",
        "https://www.cbs.gov.il/he/cbsNewBrand/Pages/מילונים-Code-lists-Classifications.aspx",
    ],
    "כתבו שמות של מדינות באפריקה": [
        "https://unstats.un.org/unsd/methodology/m49/overview/",
        "https://www.un.org/about-us/member-states",
        "https://www.cbs.gov.il/he/cbsNewBrand/Pages/מילונים-Code-lists-Classifications.aspx",
    ],
    "כתבו שמות של מדינות באסיה": [
        "https://unstats.un.org/unsd/methodology/m49/overview/",
        "https://www.un.org/about-us/member-states",
    ],
    "כתבו שמות של ערי בירה בעולם": [
        "https://www.britannica.com/topic/list-of-countries-capitals-and-currencies-2067022",
        "https://ecosocc.au.int/en/member-states",
    ],
    "כתבו שמות של גרמי שמיים במערכת השמש": [
        "https://science.nasa.gov/solar-system/planets/",
        "https://science.nasa.gov/solar-system/moons/facts/",
    ],
}
