"""Source-audited density expansion for existing open categories in batch V7.

``EXPANSION_V7`` deepens broad categories that benefit from longer rounds.
Canonicals are real category members; aliases are genuine English forms,
alternate names, stage names, identities, or established abbreviations.
Normalization-only spelling variants are intentionally omitted.
"""

from __future__ import annotations

# answer tuples: (canonical, aliases, semantic_group | None)
EXPANSION_V7: dict[str, list[tuple[str, list[str], str | None]]] = {
    "כתבו שמות של זמרים וזמרות ישראלים": [
        ("אברהם טל", ["Avraham Tal"], None),
        ("יסמין מועלם", ["Jasmin Moallem"], None),
        ("אגם בוחבוט", ["Agam Buhbut"], None),
        ("נטע ברזילי", ["Netta Barzilai", "נטע"], None),
        ("עדן גולן", ["Eden Golan"], None),
        ("מרגי", ["יהונתן מרגי", "Jonathan Mergui"], None),
        ("רן דנקר", ["Ran Danker"], None),
        ("אמיר דדון", ["Amir Dadon"], None),
        ("נתן גושן", ["Natan Goshen"], None),
        ("עמיר בניון", ["Amir Benayoun"], None),
        ("קובי אפללו", ["Kobi Aflalo"], None),
        ("משה פרץ", ["Moshe Peretz"], None),
        ("קובי פרץ", ["Kobi Peretz"], None),
        ("חיים משה", ["Haim Moshe"], None),
        ("ישי לוי", ["Ishay Levi"], None),
        ("ליאור נרקיס", ["Lior Narkis"], None),
        ("מוש בן ארי", ["Mosh Ben Ari"], None),
        ("יהורם גאון", ["Yehoram Gaon"], None),
        ("אריק סיני", ["Arik Sinai"], None),
        ("דני סנדרסון", ["Danny Sanderson"], None),
        ("גידי גוב", ["Gidi Gov"], None),
        ("יוני רכטר", ["Yoni Rechter"], None),
        ("נורית גלרון", ["Nurit Galron"], None),
        ("ריקי גל", ["Riki Gal"], None),
        ("מיקה קרני", ["Mika Karni"], None),
        ("דפנה דקל", ["Dafna Dekel"], None),
        ("רבקה זהר", ["Rivka Zohar"], None),
        ("אחינועם ניני", ["Noa", "Achinoam Nini"], None),
        ("אסתר עופרים", ["Esther Ofarim"], None),
        ("צביקה פיק", ["Svika Pick"], None),
        ("אילנה אביטל", ["Ilana Avital"], None),
        ("לאה שבת", ["Leah Shabat"], None),
        ("רמי פורטיס", ["Rami Fortis", "פורטיס"], None),
        ("טונה", ["איתי זבולון", "Tuna"], None),
        ("רביד פלוטניק", ["נצ'י נצ'", "Nechi Nech"], None),
        ("סאבלימינל", ["קובי שמעוני", "Subliminal"], None),
        ("כוורת", ["Kaveret"], None),
        ("תיסלם", ["T-Slam"], None),
        ("אתניקס", ["Ethnix"], None),
        ("טיפקס", ["Teapacks"], None),
        ("מוניקה סקס", ["Monica Sex"], None),
        ("היהודים", ["HaYehudim"], None),
        ("מרסדס בנד", ["Mercedes Band"], None),
        ("ג'ירפות", ["Giraffes"], None),
        ("החברים של נטאשה", ["Natasha's Friends"], None),
    ],
    "כתבו שמות של מאכלים ישראליים": [
        ("באבא גנוש", ["Baba ghanoush"], None),
        ("חצילים בטחינה", [], None),
        ("סלט טורקי", [], None),
        ("סלט טבולה", ["טבולה", "Tabbouleh"], None),
        ("סלט פטוש", ["פטוש", "Fattoush"], None),
        ("סלט גזר מרוקאי", [], None),
        ("סלט סלק", [], None),
        ("סלט כרוב", [], None),
        ("סלט תפוחי אדמה", [], None),
        ("איקרה", ["Ikra"], None),
        ("בוריקה", ["Brik"], None),
        ("גונדי", ["Gondi"], None),
        ("טבית", ["T'bit"], None),
        ("אושפלאו", ["פלוב", "Plov"], None),
        ("כבד קצוץ", ["Chopped liver"], None),
        ("קרפלך", ["Kreplach"], None),
        ("ורניקס", ["Vareniki"], None),
        ("קובה חמוסטה", [], "kuba"),
        ("קובה מטוגנת", [], "kuba"),
        ("קובה אורז", [], "kuba"),
        ("קציצות דגים", [], None),
        ("קציצות פראסה", ["קציצות כרישה"], None),
        ("מרק תימני", [], None),
        ("מרק רגל", [], None),
        ("מרק חרירה", ["חרירה", "Harira"], None),
        ("פלפל ממולא", [], "stuffed-vegetables"),
        ("כרוב ממולא", [], "stuffed-vegetables"),
        ("חומוס פול", [], "hummus"),
        ("שקשוקה ירוקה", [], "shakshuka"),
        ("פיתה דרוזית", [], None),
        ("לאפה", ["Laffa"], None),
        ("מנאכיש", ["מנקיש", "Manakish"], None),
        ("ספינג'", ["Sfenj"], None),
        ("בקלאווה", ["Baklava"], None),
        ("בסבוסה", ["Basbousa"], None),
        ("קדאיף", ["Kadayif"], None),
        ("שבקייה", ["Chebakia"], None),
        ("בורמואלוס", ["Burmuelos"], None),
        ("צימעס", ["Tzimmes"], None),
        ("בלינצ'ס", ["Blintzes"], None),
    ],
    "כתבו שמות של מותגי חטיפים ושוקולד": [
        ("לייז", ["Lay's"], None),
        ("ראפלס", ["Ruffles"], None),
        ("פריטוס", ["Fritos"], None),
        ("טוסטיטוס", ["Tostitos"], None),
        ("טאקיס", ["Takis"], None),
        ("סאנבייטס", ["Sunbites"], None),
        ("פופקורנרס", ["PopCorners"], None),
        ("צ'יפס אהוי", ["Chips Ahoy!"], None),
        ("ריץ", ["Ritz"], None),
        ("טוק", ["TUC"], None),
        ("בלוויטה", ["belVita"], None),
        ("גולדפיש", ["Goldfish"], None),
        ("צ'יז איט", ["Cheez-It"], None),
        ("סמארטיז", ["Smarties"], None),
        ("רולו", ["Rolo"], None),
        ("אפטר אייט", ["After Eight"], None),
        ("מילקי בר", ["Milkybar"], None),
        ("יורקי", ["Yorkie"], None),
        ("דיים", ["Daim"], None),
        ("מילקי וויי", ["Milky Way"], None),
        ("גלקסי", ["Galaxy"], None),
        ("דאב", ["Dove Chocolate"], None),
        ("שלושת המוסקטרים", ["3 Musketeers"], None),
        ("קינדר ג'וי", ["Kinder Joy"], "kinder"),
        ("קינדר סורפרייז", ["Kinder Surprise"], "kinder"),
        ("קינדר קאנטרי", ["Kinder Country"], "kinder"),
        ("קינדר שוקו בונס", ["Kinder Schoko-Bons"], "kinder"),
        ("האריבו", ["Haribo"], None),
        ("טרולי", ["Trolli"], None),
        ("סאוור פאץ' קידס", ["Sour Patch Kids"], None),
        ("צ'ופה צ'ופס", ["Chupa Chups"], None),
        ("מנטוס", ["Mentos"], None),
        ("טיק טק", ["Tic Tac"], None),
        ("ערגליות", [], None),
        ("קרמוגית", [], None),
        ("חיוכים", [], None),
        ("רבע לשבע", [], None),
        ("וופלים מן", ["Man Wafers"], None),
        ("עבאדי", ["Abadi"], None),
        ("פתי בר", ["Petit Beurre"], None),
        ("אנרג'י", ["Energy"], None),
    ],
    "כתבו שמות של גיבורי על": [
        ("וור משין", ["War Machine", "ג'יימס רודס", "רודי"], None),
        ("פלקון", ["Falcon", "סם וילסון"], None),
        ("חייל החורף", ["Winter Soldier", "באקי בארנס"], None),
        ("שאנג צ'י", ["Shang-Chi"], None),
        ("איירון פיסט", ["Iron Fist", "דני ראנד"], None),
        ("ג'סיקה ג'ונס", ["Jessica Jones"], None),
        ("המעניש", ["Punisher", "פרנק קאסל"], None),
        ("אלקטרה", ["Elektra", "אלקטרה נאצ'יוס"], None),
        ("קלוק", ["Cloak", "טיירון ג'ונסון"], None),
        ("דאגר", ["Dagger", "טנדי בואן"], None),
        ("סקווירל גירל", ["Squirrel Girl", "דורין גרין"], None),
        ("אמריקה צ'אבז", ["America Chavez", "מיס אמריקה"], None),
        ("קייט בישופ", ["Kate Bishop", "הוקאיי קייט"], None),
        ("נובה", ["Nova", "ריצ'רד ריידר"], None),
        ("סילבר סרפר", ["Silver Surfer", "נורין ראד"], None),
        ("מיסטר פנטסטיק", ["Mister Fantastic", "ריד ריצ'רדס"], None),
        ("האישה הבלתי נראית", ["Invisible Woman", "סו סטורם"], None),
        ("הלפיד האנושי", ["Human Torch", "ג'וני סטורם"], None),
        ("הדבר", ["The Thing", "בן גרים"], None),
        ("קולוסוס", ["Colossus", "פיוטר רספוטין"], None),
        ("רוג", ["Rogue", "אנה מארי"], None),
        ("גמביט", ["Gambit", "רמי לבו"], None),
        ("נייטקרולר", ["Nightcrawler", "קורט וגנר"], None),
        ("קיטי פרייד", ["Kitty Pryde", "שאדוקאט"], None),
        ("ג'ובילי", ["Jubilee", "ג'ובילי לי"], None),
        ("פסיילוק", ["Psylocke", "בטסי בראדוק"], None),
        ("אקס 23", ["X-23", "לורה קיני"], None),
        ("קייבל", ["Cable", "נתן סאמרס"], None),
        ("דומינו", ["Domino", "נינה תורמן"], None),
        ("בלו ביטל", ["Blue Beetle", "חיימה רייס"], None),
        ("בלאק קנרי", ["Black Canary", "דיינה לאנס"], None),
        ("זטאנה", ["Zatanna", "זטאנה זטארה"], None),
        ("קונסטנטין", ["John Constantine", "ג'ון קונסטנטין"], None),
        ("דוקטור פייט", ["Doctor Fate", "קנט נלסון", "Kent Nelson"], None),
        ("הוקמן", ["Hawkman", "קרטר הול"], None),
        ("הוקגירל", ["Hawkgirl", "קנדרה סונדרס"], None),
        ("אטום", ["The Atom", "ריי פאלמר"], None),
        ("פלאסטיק מן", ["Plastic Man", "פטריק אובריאן"], None),
        ("באטוומן", ["Batwoman", "קייט קיין"], None),
        ("רד הוד", ["Red Hood", "ג'ייסון טוד"], None),
        ("רייבן", ["Raven", "רייצ'ל רות'"], None),
        ("סטארפייר", ["Starfire", "קוריאנד'ר"], None),
        ("ביסט בוי", ["Beast Boy", "גאר לוגן"], None),
        ("אינוינסיבל", ["Invincible", "מארק גרייסון"], None),
        ("ספון", ["Spawn", "אל סימונס"], None),
    ],
    "כתבו שמות של דמויות מצוירות מפורסמות": [
        ("שלגיה", ["Snow White"], None),
        ("סינדרלה", ["Cinderella"], None),
        ("בל", ["Belle"], None),
        ("טיאנה", ["Tiana"], None),
        ("רפונזל", ["Rapunzel"], None),
        ("מרידה", ["Merida"], None),
        ("פוקהונטס", ["Pocahontas"], None),
        ("לילו", ["Lilo Pelekai", "Lilo"], None),
        ("טימון", ["Timon"], None),
        ("פומבה", ["Pumbaa"], None),
        ("סקאר", ["Scar"], None),
        ("מופאסה", ["Mufasa"], None),
        ("דורי", ["Dory"], None),
        ("לייטנינג מקווין", ["Lightning McQueen", "ספידי מקווין"], None),
        ("מייטר", ["Mater"], None),
        ("רמי", ["Remy"], None),
        ("וול אי", ["WALL-E"], None),
        ("איב", ["EVE"], None),
        ("שמחה", ["Joy"], None),
        ("עצב", ["Sadness"], None),
        ("פיונה", ["Princess Fiona", "Fiona"], None),
        ("החתול במגפיים", ["Puss in Boots"], None),
        ("היקאפ", ["Hiccup Horrendous Haddock", "Hiccup"], None),
        ("שום שן", ["Toothless"], None),
        ("אלכס האריה", ["Alex the Lion", "Alex"], None),
        ("מרטי הזברה", ["Marty the Zebra", "Marty"], None),
        ("מגה מוח", ["Megamind"], None),
        ("אנג", ["Aang"], None),
        ("קורה", ["Korra"], None),
        ("ג'ימי ניוטרון", ["Jimmy Neutron"], None),
        ("טימי טרנר", ["Timmy Turner"], None),
        ("דני פנטום", ["Danny Phantom"], None),
        ("סמוראי ג'ק", ["Samurai Jack"], None),
        ("דקסטר", ["Dexter"], None),
        ("ג'וני בראבו", ["Johnny Bravo"], None),
        ("פין", ["Finn the Human", "Finn"], None),
        ("ג'ייק הכלב", ["Jake the Dog", "Jake"], None),
        ("גאמבול", ["Gumball Watterson", "Gumball"], None),
        ("סטיבן יוניברס", ["Steven Universe"], None),
        ("נארוטו", ["Naruto Uzumaki", "Naruto"], None),
        ("גוקו", ["Son Goku", "Goku"], None),
        ("וג'יטה", ["Vegeta"], None),
        ("סיילור מון", ["Sailor Moon", "אוסאגי צוקינו"], None),
        ("סטואי גריפין", ["Stewie Griffin", "Stewie"], None),
        ("אריק קרטמן", ["Eric Cartman", "Cartman"], None),
    ],
    "כתבו שמות של סרטים של דיסני ופיקסאר": [
        ("פנטסיה", ["Fantasia"], None),
        ("שלושת הקבלרוס", ["The Three Caballeros"], None),
        ("הרפתקאות איכבוד ומר טוד", ["The Adventures of Ichabod and Mr. Toad"], None),
        ("היפהפייה והיחפן", ["Lady and the Tramp"], None),
        ("החרב באבן", ["The Sword in the Stone"], None),
        ("חתולים בצמרת", ["The Aristocats"], None),
        ("רובין הוד", ["Robin Hood"], None),
        ("הרפתקאות ברנרד וביאנקה", ["The Rescuers"], None),
        ("השועל והכלבלב", ["The Fox and the Hound"], None),
        ("הקדירה השחורה", ["The Black Cauldron"], None),
        ("הרפתקאותיו של סופר בלש", ["The Great Mouse Detective"], None),
        ("אוליבר וחבורתו", ["Oliver & Company", "Oliver and Company"], None),
        ("ברנרד וביאנקה במבצע אוסטרליה", ["The Rescuers Down Under"], None),
        ("דינוזאור", ["Dinosaur"], None),
        ("אחי הדוב", ["Brother Bear"], None),
        ("מרד החיות", ["Home on the Range"], None),
        ("צ'יקן ליטל", ["Chicken Little"], None),
        ("לפגוש את הרובינסונים", ["Meet the Robinsons"], None),
        ("ראלף שובר את האינטרנט", ["Ralph Breaks the Internet"], None),
        ("לשבור את הקרח 2", ["Frozen II", "Frozen 2"], None),
        ("מואנה 2", ["Moana 2"], None),
        ("זוטרופוליס 2", ["Zootopia 2"], None),
        ("צעצוע של סיפור 4", ["Toy Story 4"], None),
        ("מכוניות 2", ["Cars 2"], None),
        ("מכוניות 3", ["Cars 3"], None),
        ("משפחת סופר על 2", ["Incredibles 2", "The Incredibles 2"], None),
        ("הרפתקאות פו הדב", ["The Many Adventures of Winnie the Pooh"], None),
        ("אליאו", ["Elio"], None),
        ("Hoppers", [], None),
        ("צעצוע של סיפור 5", ["Toy Story 5"], None),
    ],
    "כתבו שמות של משחקי מחשב ווידאו": [
        ("מריו קארט", ["Mario Kart"], None),
        ("סופר סמאש ברוס", ["Super Smash Bros.", "Smash Bros"], None),
        ("אנימל קרוסינג", ["Animal Crossing"], None),
        ("ספלטון", ["Splatoon"], None),
        ("מטרויד", ["Metroid"], None),
        ("דונקי קונג", ["Donkey Kong"], None),
        ("קירבי", ["Kirby"], None),
        ("לואיג'י מנשן", ["Luigi's Mansion"], None),
        ("פיינל פנטזי", ["Final Fantasy"], None),
        ("קינגדום הארטס", ["Kingdom Hearts"], None),
        ("רזידנט איבל", ["Resident Evil"], None),
        ("סיילנט היל", ["Silent Hill"], None),
        ("מטאל גיר סוליד", ["Metal Gear Solid", "MGS"], None),
        ("דת' סטרנדינג", ["Death Stranding"], None),
        ("מונסטר האנטר", ["Monster Hunter"], None),
        ("פרסונה", ["Persona"], None),
        ("יאקוזה", ["Yakuza", "Like a Dragon"], None),
        ("באטלפילד", ["Battlefield"], None),
        ("ריינבו סיקס סיג'", ["Rainbow Six Siege", "R6 Siege"], None),
        ("דסטיני", ["Destiny"], None),
        ("וורפריים", ["Warframe"], None),
        ("בורדרלנדס", ["Borderlands"], None),
        ("פאר קריי", ["Far Cry"], None),
        ("הארת'סטון", ["Hearthstone"], None),
        ("טים פורטרס 2", ["Team Fortress 2", "TF2"], None),
        ("לפט פור דד", ["Left 4 Dead"], None),
        ("גארי'ס מוד", ["Garry's Mod", "GMod"], None),
        ("טרריה", ["Terraria"], None),
        ("סטארדיו ואלי", ["Stardew Valley"], None),
        ("הולו נייט", ["Hollow Knight"], None),
        ("היידס", ["Hades"], None),
        ("סלסט", ["Celeste"], None),
        ("קאפהד", ["Cuphead"], None),
        ("אנדרטייל", ["Undertale"], None),
        ("דד סלס", ["Dead Cells"], None),
        ("סאבווי סרפרס", ["Subway Surfers"], None),
        ("טמפל ראן", ["Temple Run"], None),
        ("פרוט נינג'ה", ["Fruit Ninja"], None),
        ("פוקימון גו", ["Pokémon GO", "Pokemon Go"], None),
        ("היי דיי", ["Hay Day"], None),
        ("קווין מאסטר", ["Coin Master"], None),
        ("אן בי איי 2K", ["NBA 2K"], None),
        ("פוטבול מנג'ר", ["Football Manager"], None),
        ("גראן טוריסמו", ["Gran Turismo"], None),
        ("פורצה הורייזון", ["Forza Horizon"], None),
        ("וור ת'אנדר", ["War Thunder"], None),
        ("איט טייקס טו", ["It Takes Two"], None),
        ("דיסקו אליסיום", ["Disco Elysium"], None),
        ("בלדורז גייט", ["Baldur's Gate"], None),
        ("מייפל סטורי", ["MapleStory", "Maple Story"], None),
    ],
    "כתבו שמות של סוגי ממתקים": [
        ("שומשומייה", ["Sesame brittle"], None),
        ("בריטל בוטנים", ["Peanut brittle"], None),
        ("שקדים מסוכרים", ["Candied almonds"], None),
        ("ג'ורדן אלמונדס", ["Jordan almonds"], None),
        ("ג'ינג'ר מסוכר", ["Candied ginger"], None),
        ("קליפות תפוז מסוכרות", ["Candied orange peel"], None),
        ("תפוח מסוכר", ["Candy apple", "Candied apple"], None),
        ("תפוח קרמל", ["Caramel apple"], None),
        ("דובדבנים מצופים שוקולד", ["Chocolate-covered cherries"], None),
        ("פולי קפה מצופים שוקולד", ["Chocolate-covered coffee beans"], None),
        ("בארק שוקולד", ["Chocolate bark"], None),
        ("כפתורי שוקולד", ["Chocolate buttons"], None),
        ("פפרמינט בארק", ["Peppermint bark"], None),
        ("פפרמינט פאטי", ["Peppermint patty"], None),
        ("כוסיות חמאת בוטנים", ["Peanut butter cups"], None),
        ("קנדי קורן", ["Candy corn"], None),
        ("ג'לי בייביז", ["Jelly babies"], "jelly-candy"),
        ("ויין גאמס", ["Wine gums"], "gummy"),
        ("סוכריות פירות לעיסות", ["Fruit chews"], None),
        ("ליקריץ אולסורטס", ["Liquorice allsorts", "Licorice allsorts"], None),
        ("גלגלי ליקריץ", ["Liquorice wheels", "Licorice wheels"], None),
        ("שרשרת סוכריות", ["Candy necklace"], None),
        ("צמיד סוכריות", ["Candy bracelet"], None),
        ("סוכריות שרבט", ["Sherbet candy"], None),
        ("אבקה חמוצה", ["Sour candy powder"], None),
        ("סוכריות דחוסות", ["Pressed candy", "Tablet candy"], None),
        ("סוכריות ממולאות", ["Filled hard candy"], None),
        ("קרמל מלוח", ["Salted caramel"], "caramel"),
        ("טאפי מי מלח", ["Salt water taffy"], "taffy"),
        ("נוגט לבן", ["White nougat"], "nougat"),
    ],
    "כתבו שמות של חיות משק וחווה": [
        ("סוס עבודה", ["Draft horse"], "horse"),
        ("פוני", ["Pony"], "horse"),
        ("עגלה", ["Heifer"], "cattle"),
        ("ביזון", ["Bison"], None),
        ("אייל אדום", ["Red deer"], None),
        ("אייל נקוד", ["Fallow deer"], None),
        ("ננדו", ["Rhea"], None),
        ("פורל", ["Trout"], None),
        ("סלמון", ["Salmon"], None),
        ("שפמנון", ["Catfish"], None),
        ("חדקן", ["Sturgeon"], None),
        ("דניס", ["Gilthead seabream", "Sea bream"], None),
        ("לברק", ["Sea bass"], None),
        ("בורי", ["Mullet"], None),
        ("שרימפס", ["Shrimp", "Prawn"], None),
        ("סרטן נהרות", ["Crayfish", "Crawfish"], None),
        ("צדפה", ["Oyster"], None),
        ("מולה", ["מולים", "Mussel"], None),
        ("חילזון", ["Farmed snail"], None),
        ("תולעת משי", ["Silkworm"], None),
        ("תולעת קמח", ["Mealworm"], None),
        ("צרצר", ["Cricket"], None),
    ],
    "כתבו דברים שמוצאים במטבח": [
        ("צלוחית", ["Saucer"], None),
        ("קנקן", ["Pitcher", "Jug"], None),
        ("תרמוס", ["Vacuum flask", "Thermos"], None),
        ("דקנטר", ["Decanter"], None),
        ("כוס יין", ["Wine glass"], None),
        ("כוס שוט", ["Shot glass"], None),
        ("סוטאז'", ["Sauté pan", "Saute pan"], None),
        ("סיר מרק", ["Stockpot"], None),
        ("סיר הולנדי", ["Dutch oven"], None),
        ("תבנית צלייה", ["Roasting pan"], None),
        ("תבנית מאפינס", ["Muffin tin"], None),
        ("תבנית אינגליש קייק", ["Loaf pan"], None),
        ("תבנית פיצה", ["Pizza pan"], None),
        ("אבן פיצה", ["Pizza stone"], None),
        ("כפות מדידה", ["Measuring spoons"], None),
        ("טיימר מטבח", ["Kitchen timer"], None),
        ("מדחום למזון", ["Food thermometer", "Meat thermometer"], None),
        ("כפפת תנור", ["Oven mitt"], None),
        ("תחתית לסיר", ["Trivet"], None),
        ("משפך", ["Funnel"], None),
        ("מסחטת הדרים", ["Citrus juicer"], None),
        ("חותכן פיצה", ["Pizza cutter", "Pizza wheel"], None),
        ("כף גלידה", ["Ice cream scoop"], None),
        ("פותחן בקבוקים", ["Bottle opener"], None),
        ("בלנדר מוט", ["Immersion blender", "Stick blender"], None),
        ("מיקסר ידני", ["Hand mixer"], None),
        ("סיר אורז", ["Rice cooker"], None),
        ("טוסטר לחיצה", ["Sandwich press", "Panini press"], None),
        ("מכשיר ופל", ["Waffle maker", "Waffle iron"], None),
        ("מכונת לחם", ["Bread maker", "Bread machine"], None),
        ("מכונת גלידה", ["Ice cream maker"], None),
        ("מייבש מזון", ["Food dehydrator"], None),
        ("מכשיר סו ויד", ["Sous vide", "Immersion circulator"], None),
        ("קולט אדים", ["Range hood", "Extractor hood"], None),
        ("אי מטבח", ["Kitchen island"], None),
        ("מזווה", ["Pantry"], None),
        ("נייר מגבת", ["Paper towel"], None),
        ("מברשת כלים", ["Dish brush"], None),
        ("כפפות גומי", ["Dishwashing gloves"], None),
        ("טבליות למדיח", ["Dishwasher tablets"], None),
    ],
    "כתבו שמות של ירקות ירוקים": [
        ("רומנסקו", ["Romanesco"], None),
        ("אפונת שלג", ["Snow peas"], None),
        ("אפונת סוכר", ["Sugar snap peas", "Snap peas"], None),
        ("פול ירוק", ["Fava beans", "Broad beans"], None),
        ("עלי חרדל", ["Mustard greens"], None),
        ("עלי קולרד", ["Collard greens"], None),
        ("אנדיב", ["Endive"], None),
        ("אסקרול", ["Escarole"], None),
        ("חומעה", ["Sorrel"], None),
        ("ריג'לה", ["רגלת הגינה", "Purslane"], None),
        ("מיזונה", ["Mizuna"], None),
        ("רפיני", ["Broccoli rabe", "Rapini"], None),
        ("ברוקולי סיני", ["Gai lan", "Chinese broccoli"], None),
        ("צ'יוטה", ["Chayote"], None),
        ("מלון מר", ["Bitter melon", "Bitter gourd"], None),
        ("שום ירוק", ["Green garlic"], None),
        ("למון גראס", ["עשב לימון", "Lemongrass"], None),
        ("טרגון", ["Tarragon"], None),
        ("רוזמרין", ["Rosemary"], None),
        ("עלי סלק", ["Beet greens"], None),
        ("עלי לפת", ["Turnip greens"], None),
        ("נבטי אלפלפה", ["Alfalfa sprouts"], None),
    ],
    "כתבו שמות של פירות טרופיים": [
        ("קיוואנו", ["Horned melon", "African horned cucumber"], None),
        ("פיג'ואה", ["Feijoa", "Pineapple guava"], None),
        ("טמרילו", ["Tamarillo", "Tree tomato"], None),
        ("פפינו", ["Pepino melon", "Pepino dulce"], None),
        ("קופואסו", ["Cupuaçu", "Cupuacu"], None),
        ("לוקומה", ["Lucuma"], None),
        ("ג'בוטיקבה", ["Jabuticaba"], None),
        ("אקי", ["Ackee"], None),
        ("פרי הנס", ["Miracle fruit"], None),
        ("תפוח קשיו", ["Cashew apple"], None),
        ("פרי קקאו", ["Cacao fruit", "Cocoa pod"], None),
        ("ממונסיו", ["Mamoncillo", "Spanish lime"], None),
        ("אמברלה", ["Ambarella", "June plum"], None),
        ("תפוח ורד", ["Rose apple"], None),
        ("תפוח שעווה", ["Wax apple", "Java apple"], None),
        ("קומקוואט", ["Kumquat"], None),
        ("ליים", ["Lime"], None),
        ("פרי מונסטרה", ["Monstera deliciosa fruit", "Ceriman"], None),
    ],
    "כתבו שמות של מוצרי איפור": [
        ("שפתון נוזלי", ["Liquid lipstick"], "lipstick"),
        ("שפתון מאט", ["Matte lipstick"], "lipstick"),
        ("שפתון לחות", ["Tinted lip balm"], "lipstick"),
        ("שמן שפתיים", ["Lip oil"], None),
        ("ליפ פלאמפר", ["מגדיל שפתיים", "Lip plumper"], None),
        ("פלטת צלליות", ["Eyeshadow palette"], "eyeshadow"),
        ("צללית סטיק", ["Eyeshadow stick"], "eyeshadow"),
        ("אייליינר עיפרון", ["Pencil eyeliner"], "eyeliner"),
        ("קוהל", ["Kohl", "Kajal"], "eyeliner"),
        ("פריימר לעיניים", ["Eye primer", "Eyeshadow primer"], "primer"),
        ("פריימר לריסים", ["Lash primer", "Mascara primer"], "primer"),
        ("פומייד גבות", ["Brow pomade"], "brow-gel"),
        ("שעוות גבות", ["Brow wax"], "brow-gel"),
        ("סבון גבות", ["Soap brows", "Brow soap"], "brow-gel"),
        ("טוש גבות", ["Brow pen", "Brow marker"], None),
        ("סומק קרם", ["Cream blush"], "blush"),
        ("סומק נוזלי", ["Liquid blush"], "blush"),
        ("סומק סטיק", ["Blush stick"], "blush"),
        ("ברונזר קרם", ["Cream bronzer"], "bronzer"),
        ("היילייטר נוזלי", ["Liquid highlighter"], "highlighter"),
        ("היילייטר סטיק", ["Highlighter stick"], "highlighter"),
        ("קונטור סטיק", ["Contour stick"], "contour"),
        ("מייקאפ נוזלי", ["Liquid foundation"], "foundation"),
        ("מייקאפ מינרלי", ["Mineral foundation"], "foundation"),
        ("מייקאפ קושן", ["Cushion foundation"], "foundation"),
        ("קרם לחות עם גוון", ["Tinted moisturizer"], "foundation"),
        ("צבע פנים", ["Face paint"], None),
    ],
    "כתבו שמות של פרחים": [
        ("אסטר", ["Aster"], None),
        ("זיניה", ["Zinnia"], None),
        ("קוסמוס", ["Cosmos flower"], None),
        ("בגוניה", ["Begonia"], None),
        ("פוקסיה", ["Fuchsia"], None),
        ("קמומיל", ["בבונג", "Chamomile"], None),
        ("דרדר", ["Cornflower"], None),
        ("דורבנית", ["Delphinium", "Larkspur"], None),
        ("תורמוס", ["Lupine", "Lupin"], None),
        ("אפונה ריחנית", ["Sweet pea"], None),
        ("קלמטיס", ["Clematis"], None),
        ("לפופית", ["Morning glory"], None),
        ("יערה", ["Honeysuckle"], None),
        ("הרדוף הנחלים", ["Oleander"], None),
        ("לנטנה", ["Lantana"], None),
        ("בשמת", ["Impatiens"], None),
        ("בכור אביב", ["Primrose", "Primula"], None),
        ("אכילאה", ["Yarrow", "Achillea"], None),
        ("גאילרדיה", ["Gaillardia", "Blanket flower"], None),
        ("אכינצאה", ["Echinacea", "Coneflower"], None),
        ("ורוניקה", ["Speedwell", "Veronica flower"], None),
        ("מימוזה", ["Mimosa flower"], None),
        ("פרח שעווה", ["Waxflower"], None),
        ("מוסקרי", ["Grape hyacinth", "Muscari"], None),
        ("איקסיה", ["Ixia"], None),
        ("חבצלת החוף", ["Sea daffodil"], None),
        ("דם המכבים", ["Helichrysum sanguineum"], None),
        ("בן חצב", ["Scilla"], None),
        ("לוטם", ["Rockrose", "Cistus"], None),
        ("חלמית", ["Mallow"], None),
        ("חוטמית", ["Hollyhock"], None),
        ("קיפודן", ["Globe thistle", "Echinops"], None),
        ("נר הלילה", ["Evening primrose"], None),
        ("נימפאה", ["שושנת מים", "Water lily"], None),
    ],
    "כתבו שמות של בעלי חיים שחיים בים": [
        ("פינגווין", ["Penguin"], None),
        ("לוטרת ים", ["Sea otter"], None),
        ("אלבטרוס", ["Albatross"], None),
        ("שחף", ["Seagull", "Gull"], None),
        ("קורמורן", ["Cormorant"], None),
        ("שקנאי", ["Pelican"], None),
        ("מרלין", ["Marlin"], None),
        ("דג שמש", ["Ocean sunfish", "Mola mola"], None),
        ("דג מעופף", ["Flying fish"], None),
        ("דקר", ["Grouper"], None),
        ("טורבוט", ["Turbot"], None),
        ("לברק", ["Sea bass"], None),
        ("בורי", ["Mullet"], None),
        ("סולית", ["Sole"], None),
        ("פלנדר", ["Flounder"], None),
        ("דג פרפר", ["Butterflyfish"], None),
        ("נתחן", ["Surgeonfish"], None),
        ("נצרן", ["Triggerfish"], None),
        ("קברנון", ["Goby"], None),
        ("סבידה", ["Cuttlefish"], None),
        ("קריל", ["Krill"], None),
        ("בלוט ים", ["Barnacle"], None),
        ("סרטן נזיר", ["Hermit crab"], None),
        ("סרטן פרסה", ["Horseshoe crab"], None),
        ("אויסטר", ["צדפת מאכל", "Oyster"], None),
        ("מולה", ["מולים", "Mussel"], None),
        ("סקאלופ", ["Scallop"], None),
        ("אבלון", ["Abalone"], None),
        ("דולר חול", ["Sand dollar"], None),
        ("נחשון ים", ["Brittle star"], None),
        ("חבצלת ים", ["Sea lily", "Crinoid"], None),
        ("עכביש ים", ["Sea spider"], None),
        ("שלפוחן מצוי", ["Portuguese man o' war", "Man-of-war"], None),
        ("ארנבת ים", ["Sea hare"], None),
    ],
}


CURATION_SOURCES: dict[str, list[str]] = {
    "כתבו שמות של זמרים וזמרות ישראלים": [
        "https://acum.org.il/",
        "https://www.kan.org.il/content/archive1/archivemusic/",
    ],
    "כתבו שמות של מאכלים ישראליים": [
        "https://www.nli.org.il/en/discover/israel-culture-and-society/israeli-food/israeli-kitchen",
        "https://en.wikipedia.org/wiki/List_of_Israeli_dishes",
    ],
    "כתבו שמות של מותגי חטיפים ושוקולד": [
        "https://www.osem-nestle.co.il/brands",
        "https://www.strauss-group.com/brands/",
        "https://www.ferrero.com/int/en/our-brands",
    ],
    "כתבו שמות של גיבורי על": [
        "https://www.marvel.com/characters",
        "https://www.dc.com/characters",
    ],
    "כתבו שמות של דמויות מצוירות מפורסמות": [
        "https://characters.disney.com/",
        "https://www.warnerbros.com/brands/looney-tunes",
        "https://www.nick.com/shows",
    ],
    "כתבו שמות של סרטים של דיסני ופיקסאר": [
        "https://disneyanimation.com/films/",
        "https://www.pixar.com/feature-films/",
    ],
    "כתבו שמות של משחקי מחשב ווידאו": [
        "https://www.esrb.org/search/",
        "https://www.mobygames.com/game/",
    ],
    "כתבו שמות של סוגי ממתקים": [
        "https://www.britannica.com/topic/candy-food",
        "https://en.wikipedia.org/wiki/List_of_candies",
    ],
    "כתבו שמות של חיות משק וחווה": [
        "https://www.fao.org/livestock-systems/en/",
        "https://www.fao.org/4/cc0461en/online/sofia/2022/aquaculture-production.html",
        "https://www.fao.org/edible-insects/en/",
    ],
    "כתבו דברים שמוצאים במטבח": [
        "https://www.fda.gov/food/buy-store-serve-safe-food/safe-food-handling",
        "https://www.osha.gov/etools/hospitals/food-services/kitchen-equipment",
    ],
    "כתבו שמות של ירקות ירוקים": [
        "https://www.myplate.gov/eat-healthy/vegetables",
        "https://fdc.nal.usda.gov/",
    ],
    "כתבו שמות של פירות טרופיים": [
        "https://www.fao.org/markets-and-trade/commodities-overview/commodities/tropical-fruits/en",
        "https://en.wikipedia.org/wiki/Tropical_fruit",
    ],
    "כתבו שמות של מוצרי איפור": [
        "https://www.fda.gov/cosmetics/cosmetic-products/makeup",
        "https://www.fda.gov/cosmetics/registration-listing-cosmetic-product-facilities-and-products/cosmetic-product-categories-and-codes",
        "https://www.sephora.com/shop/makeup-cosmetics",
    ],
    "כתבו שמות של פרחים": [
        "https://www.kew.org/science/collections-and-resources/data-and-digital/names-and-taxonomy",
        "https://www.rhs.org.uk/plants/search-form",
    ],
    "כתבו שמות של בעלי חיים שחיים בים": [
        "https://www.fisheries.noaa.gov/find-species",
        "https://www.marinespecies.org/",
    ],
}
