"""First standalone batch of broad Hebrew party-trivia categories for V10.

The entries use familiar Hebrew canonicals with genuine spelling, translated,
or original-language aliases where those forms identify the same answer.
"""

from __future__ import annotations

# answer tuples: (canonical, aliases, semantic_group | None)
NEW_QUESTIONS_V10: list[dict] = [
    {
        "text": "כתבו מילים בסלנג ישראלי",
        "answers": [
            ("סבבה", ["סבבה לגמרי"], None),
            ("אחלה", ["אחלה בחלה"], None),
            ("יאללה", ["יאלה"], None),
            ("וואלה", ["ואלה"], None),
            ("באסה", ["בעסה"], None),
            ("סחתיין", ["סחטיין"], None),
            ("חבל על הזמן", ["חבלז"], None),
            ("פדיחה", ["פדיחות"], None),
            ("דוגרי", ["דוגרית"], None),
            ("תכלס", ["תכל'ס"], None),
            ("קטע", ["איזה קטע"], None),
            ("מגניב", ["מגניבה"], None),
            ("קול", ["קוּל"], None),
            ("זורם", ["זורמת"], None),
            ("לפרגן", ["פירגון", "פרגון"], None),
            ("לחפור", ["חופר", "חופרת"], None),
            ("להתבאס", ["התבאס", "מבואס"], None),
            ("להבריז", ["הבריז", "מבריז"], None),
            ("להתפדח", ["התפדח", "מתפדח"], None),
            ("חפיף", ["חפיפניק"], None),
            ("על הפנים", ["על הפנים ממש"], None),
            ("אש", ["אש עליך"], None),
            ("קטלני", ["קטלנית"], None),
            ("נדיר", ["נדירה"], None),
            ("מטורף", ["מטורפת"], None),
            ("פצצה", ["פצצתי"], None),
            ("גבר", ["גבר גבר"], None),
            ("נשמה", ["נשמה שלי"], None),
            ("אחי", ["אחשלי", "אח שלי"], None),
            ("כפרה", ["כפרה עליך", "כפרה עלייך"], None),
            ("סגור", ["סגרנו"], None),
            ("בכיף", ["בכיף שלי"], None),
            ("בקטנה", ["קטנה עלינו"], None),
            ("שוס", ["השוס"], None),
            ("סטלה", ["בסטלה"], None),
            ("חרפן", ["מחרפן", "מחרפנת"], None),
            ("בול", ["בול בפוני"], None),
            ("כאילו", ["כזה כאילו"], None),
            ("עפתי", ["עף על זה", "עפה על זה"], None),
            ("פגז", ["פגזי"], None),
        ],
    },
    {
        "text": "כתבו דברים שיש במקרר",
        "answers": [
            ("חלב", ["קרטון חלב"], None),
            ("ביצים", ["ביצה"], None),
            ("גבינה", ["גבינות"], None),
            ("קוטג'", ["קוטג"], None),
            ("יוגורט", ["יוגורטים"], None),
            ("חמאה", ["חמאה מלוחה"], None),
            ("ירקות", ["ירק"], None),
            ("פירות", ["פרי"], None),
            ("עגבניות", ["עגבנייה", "עגבניה"], None),
            ("מלפפונים", ["מלפפון"], None),
            ("פלפלים", ["פלפל"], None),
            ("גזר", ["גזרים"], None),
            ("חסה", ["ראש חסה"], None),
            ("בצל", ["בצלים"], None),
            ("תפוחים", ["תפוח"], None),
            ("לימונים", ["לימון"], None),
            ("מיץ", ["בקבוק מיץ"], None),
            ("מים", ["בקבוק מים"], None),
            ("סודה", ["מי סודה"], None),
            ("בירה", ["בקבוק בירה"], None),
            ("יין", ["בקבוק יין"], None),
            ("ריבה", ["קונפיטורה"], None),
            ("מיונז", ["מיוֹנז"], None),
            ("קטשופ", ["רוטב קטשופ"], None),
            ("חרדל", ["ממרח חרדל"], None),
            ("טחינה", ["טחינה מוכנה"], None),
            ("חומוס", ["ממרח חומוס"], None),
            ("זיתים", ["זית"], None),
            ("חמוצים", ["ירקות כבושים"], None),
            ("נקניק", ["נקניקים"], None),
            ("פסטרמה", ["נקניק פסטרמה"], None),
            ("שאריות", ["שאריות אוכל"], None),
            ("קופסאות אוכל", ["קופסת אוכל"], None),
            ("תרופות", ["תרופה"], None),
            ("שוקולד", ["חפיסת שוקולד"], None),
            ("שמנת", ["שמנת מתוקה"], None),
            ("גבינה צהובה", ["פרוסות גבינה צהובה"], None),
            ("גבינה לבנה", ["גביע גבינה לבנה"], None),
            ("חלב סויה", ["משקה סויה"], None),
            ("רוטב", ["רטבים"], None),
        ],
    },
    {
        "text": "כתבו דברים שלוקחים לים",
        "answers": [
            ("מגבת", ["מגבת חוף", "מגבת ים"], None),
            ("בגד ים", ["בגדי ים"], None),
            ("קרם הגנה", ["קרם שיזוף", "מסנן קרינה"], None),
            ("כובע", ["כובע שמש"], None),
            ("משקפי שמש", ["משקפיים נגד שמש"], None),
            ("מים", ["בקבוק מים"], None),
            ("צידנית", ["צידנית אוכל"], None),
            ("שמשייה", ["שמשיה"], None),
            ("כיסא ים", ["כיסא חוף"], None),
            ("מחצלת", ["מחצלת ים"], None),
            ("כפכפים", ["כפכפי ים"], None),
            ("סנדלים", ["סנדלי ים"], None),
            ("כדור", ["כדור ים"], None),
            ("מטקות", ["מטקה"], None),
            ("גלשן", ["גלשן גלים"], None),
            ("בוגי", ["גלשן בוגי"], None),
            ("שנורקל", ["קנה נשימה"], None),
            ("מסכת צלילה", ["מסכה לצלילה"], None),
            ("סנפירים", ["סנפירי שחייה"], None),
            ("תיק", ["תיק ים"], None),
            ("טלפון", ["טלפון נייד"], None),
            ("ספר", ["ספר קריאה"], None),
            ("אוזניות", ["אוזניות אלחוטיות"], None),
            ("רמקול", ["רמקול נייד"], None),
            ("אוכל", ["אוכל לים"], None),
            ("פירות", ["פרי"], None),
            ("חטיפים", ["חטיף"], None),
            ("כריכים", ["כריך", "סנדוויצ'ים"], None),
            ("בירה", ["בקבוק בירה"], None),
            ("כסף", ["מזומן"], None),
            ("מפתחות", ["מפתח"], None),
            ("בגדים להחלפה", ["בגדי החלפה"], None),
            ("שקית", ["שקית ניילון"], None),
            ("צעצועי חול", ["משחקי חול"], None),
            ("דלי", ["דלי חול"], None),
            ("כף", ["כף לחול"], None),
            ("אוהל", ["אוהל חוף"], None),
            ("ערסל", ["ערסל חוף"], None),
            ("משקפת", ["משקפת שדה"], None),
            ("מצלמה", ["מצלמת חוף"], None),
        ],
    },
    {
        "text": "כתבו שמות של תוכניות ריאליטי",
        "answers": [
            ("האח הגדול", ["Big Brother"], None),
            ("הישרדות", ["Survivor"], None),
            ("מאסטר שף", ["MasterChef", "Master Chef"], None),
            ("נינג'ה ישראל", ["נינג'ה", "Ninja Israel"], None),
            ("הכוכב הבא", ["Rising Star"], None),
            ("אקס פקטור", ["The X Factor", "X Factor"], None),
            ("דה וויס", ["The Voice"], None),
            ("רוקדים עם כוכבים", ["Dancing with the Stars"], None),
            ("המירוץ למיליון", ["The Amazing Race"], None),
            ("חתונה ממבט ראשון", ["חתונמי", "Married at First Sight"], None),
            ("אהבה חדשה", ["New Love"], None),
            ("בואו לאכול איתי", ["Come Dine with Me"], None),
            ("משחקי השף", ["Game of Chefs"], None),
            ("המטבח המנצח", ["MKR", "My Kitchen Rules"], None),
            ("פקין אקספרס", ["Peking Express"], None),
            ("גולסטאר", ["Goalstar"], None),
            ("המעושרות", ["The Rich Women"], None),
            ("מחוברים", ["Mehubarim", "Connected"], None),
            ("דייט בחשיכה", ["Dating in the Dark"], None),
            ("בייק אוף ישראל", ["Bake Off Israel"], None),
            ("בית ספר למוסיקה", ["בית ספר למוזיקה"], None),
            ("פרויקט מסלול", ["Project Runway"], None),
            ("הטופ מודל הבאה", ["America's Next Top Model", "ANTM"], None),
            ("אמריקן איידול", ["American Idol"], None),
            ("בריטיין גוט טאלנט", ["Britain's Got Talent", "BGT"], None),
            ("לאב איילנד", ["Love Island"], None),
            ("חם מדי לגעת", ["Too Hot to Handle"], None),
            ("המעגל", ["The Circle"], None),
            ("הרווק", ["The Bachelor"], None),
            ("הרווקה", ["The Bachelorette"], None),
            ("המרוץ לדראג של רו פול", ["RuPaul's Drag Race", "Drag Race"], None),
            ("שארק טנק", ["Shark Tank"], None),
            ("מטבחי הגיהינום", ["Hell's Kitchen"], None),
            (
                "קיצ'ן נייטמרס",
                ["Kitchen Nightmares", "Ramsay's Kitchen Nightmares"],
                None,
            ),
            ("המתמחה", ["The Apprentice"], None),
            ("עין קווירית", ["Queer Eye"], None),
            ("מסודרים בלוס אנג'לס", ["Selling Sunset"], None),
            ("הזמר במסכה", ["The Masked Singer"], None),
            ("לגו מאסטרס", ["LEGO Masters", "Lego Masters"], None),
            ("טופ שף", ["Top Chef"], None),
        ],
    },
    {
        "text": 'כתבו שמות של דמויות מהתנ"ך',
        "answers": [
            ("אדם", ["Adam", "אדם הראשון"], None),
            ("חוה", ["Eve", "חווה"], None),
            ("קין", ["Cain"], None),
            ("הבל", ["Abel"], None),
            ("נח", ["Noah", "נוח"], None),
            ("אברהם", ["Abraham", "אברם"], None),
            ("שרה", ["Sarah", "שרי"], None),
            ("יצחק", ["Isaac"], None),
            ("רבקה", ["Rebecca", "Rebekah"], None),
            ("יעקב", ["Jacob", "ישראל אבינו"], None),
            ("רחל", ["Rachel"], None),
            ("לאה", ["Leah"], None),
            ("יוסף", ["Joseph", "יוסף הצדיק"], None),
            ("משה", ["Moses", "משה רבנו"], None),
            ("אהרן", ["Aaron", "אהרון"], None),
            ("מרים", ["Miriam", "מרים הנביאה"], None),
            ("יהושע", ["Joshua", "יהושע בן נון"], None),
            ("דבורה", ["Deborah", "דבורה הנביאה"], None),
            ("שמשון", ["Samson", "שמשון הגיבור"], None),
            ("דלילה", ["Delilah"], None),
            ("שאול", ["Saul", "שאול המלך"], None),
            ("דוד", ["David", "דוד המלך"], None),
            ("שלמה", ["Solomon", "שלמה המלך"], None),
            ("רות", ["Ruth", "רות המואבייה"], None),
            ("נעמי", ["Naomi"], None),
            ("אסתר", ["Esther", "הדסה"], None),
            ("מרדכי", ["Mordecai", "מרדכי היהודי"], None),
            ("המן", ["Haman", "המן האגגי"], None),
            ("איוב", ["Job"], None),
            ("יונה", ["Jonah", "יונה הנביא"], None),
            ("אליהו", ["Elijah", "אליהו הנביא"], None),
            ("אלישע", ["Elisha", "אלישע הנביא"], None),
            ("ישעיהו", ["Isaiah", "ישעיה"], None),
            ("ירמיהו", ["Jeremiah", "ירמיה"], None),
            ("יחזקאל", ["Ezekiel", "יחזקאל הנביא"], None),
            ("דניאל", ["Daniel", "דניאל הנביא"], None),
            ("שמואל", ["Samuel", "שמואל הנביא"], None),
            ("גדעון", ["Gideon", "גדעון השופט"], None),
            ("בת שבע", ["Bathsheba", "בתשבע"], None),
            ("גוליית", ["Goliath", "גלית"], None),
        ],
    },
    {
        "text": "כתבו שמות של דמויות מהארי פוטר",
        "answers": [
            ("הארי פוטר", ["Harry Potter", "הארי"], None),
            ("הרמיוני גריינג'ר", ["Hermione Granger", "הרמיוני"], None),
            ("רון ויזלי", ["Ron Weasley", "רונלד ויזלי"], None),
            ("אלבוס דמבלדור", ["Albus Dumbledore", "דמבלדור"], None),
            ("לורד וולדמורט", ["Lord Voldemort", "וולדמורט", "טום רידל"], None),
            ("סוורוס סנייפ", ["Severus Snape", "סנייפ"], None),
            ("מינרווה מקגונגל", ["Minerva McGonagall", "מקגונגל"], None),
            ("רובאוס האגריד", ["Rubeus Hagrid", "האגריד"], None),
            ("דראקו מאלפוי", ["Draco Malfoy", "דראקו"], None),
            ("סיריוס בלק", ["Sirius Black", "סיריוס"], None),
            ("רמוס לופין", ["Remus Lupin", "לופין"], None),
            ("בלטריקס לסטריינג'", ["Bellatrix Lestrange", "בלטריקס"], None),
            ("נוויל לונגבוטום", ["Neville Longbottom", "נוויל"], None),
            ("לונה לאבגוד", ["Luna Lovegood", "לונה"], None),
            ("ג'יני ויזלי", ["Ginny Weasley", "ג'יני"], None),
            ("פרד ויזלי", ["Fred Weasley", "פרד"], None),
            ("ג'ורג' ויזלי", ["George Weasley", "ג'ורג'"], None),
            ("מולי ויזלי", ["Molly Weasley", "מולי"], None),
            ("ארתור ויזלי", ["Arthur Weasley", "ארתור"], None),
            ("דובי", ["Dobby", "דובי גמדון הבית"], None),
            ("קריצ'ר", ["Kreacher"], None),
            ("הדוויג", ["Hedwig"], None),
            ("צ'ו צ'אנג", ["Cho Chang", "צ'ו"], None),
            ("סדריק דיגורי", ["Cedric Diggory", "סדריק"], None),
            ("פלר דלאקור", ["Fleur Delacour", "פלר"], None),
            ("ויקטור קרום", ["Viktor Krum", "קרום"], None),
            ("עין הזעם מודי", ["Mad-Eye Moody", "Alastor Moody", "אלאסטור מודי"], None),
            ("לוציוס מאלפוי", ["Lucius Malfoy", "לוציוס"], None),
            ("נרקיסה מאלפוי", ["Narcissa Malfoy", "נרקיסה"], None),
            ("פיטר פטיגרו", ["Peter Pettigrew", "זנב תולע", "Wormtail"], None),
            ("דולורס אמברידג'", ["Dolores Umbridge", "אמברידג'"], None),
            ("ארגוס פילץ'", ["Argus Filch", "פילץ'"], None),
            ("סיביל טרלוני", ["Sybill Trelawney", "טרלוני"], None),
            ("הוראס סלגהורן", ["Horace Slughorn", "סלגהורן"], None),
            ("קוויריניוס קווירל", ["Quirinus Quirrell", "קווירל"], None),
            ("גילדרוי לוקהרט", ["Gilderoy Lockhart", "לוקהרט"], None),
            ("מירטל המייללת", ["Moaning Myrtle", "מירטל"], None),
            ("ניק כמעט בלי ראש", ["Nearly Headless Nick", "ניק"], None),
            ("גאריק אוליבנדר", ["Garrick Ollivander", "אוליבנדר"], None),
            ("שיימוס פיניגן", ["Seamus Finnigan", "שיימוס"], None),
        ],
    },
    {
        "text": "כתבו שמות של זמרים בינלאומיים",
        "answers": [
            ("טיילור סוויפט", ["Taylor Swift", "Swift"], None),
            ("ביונסה", ["Beyoncé", "Beyonce"], None),
            ("אדל", ["Adele", "Adele Adkins"], None),
            ("אד שירן", ["Ed Sheeran", "Sheeran"], None),
            ("ברונו מארס", ["Bruno Mars", "Peter Hernandez"], None),
            ("ליידי גאגא", ["Lady Gaga", "Stefani Germanotta"], None),
            ("ריהאנה", ["Rihanna", "Robyn Fenty"], None),
            ("ג'סטין ביבר", ["Justin Bieber", "Bieber"], None),
            ("אריאנה גרנדה", ["Ariana Grande", "Grande"], None),
            ("בילי אייליש", ["Billie Eilish", "Eilish"], None),
            ("דה ויקנד", ["The Weeknd", "Abel Tesfaye"], None),
            ("דרייק", ["Drake", "Aubrey Graham"], None),
            ("מדונה", ["Madonna", "Madonna Ciccone"], None),
            ("מייקל ג'קסון", ["Michael Jackson", "MJ"], None),
            ("אלביס פרסלי", ["Elvis Presley", "Elvis"], None),
            ("ויטני יוסטון", ["Whitney Houston", "Whitney"], None),
            ("מריה קארי", ["Mariah Carey", "Mariah"], None),
            ("סלין דיון", ["Céline Dion", "Celine Dion"], None),
            ("שאקירה", ["Shakira", "Shakira Mebarak"], None),
            ("ג'ניפר לופז", ["Jennifer Lopez", "J.Lo", "JLo"], None),
            ("בריטני ספירס", ["Britney Spears", "Britney"], None),
            ("כריסטינה אגילרה", ["Christina Aguilera", "Xtina"], None),
            ("קייטי פרי", ["Katy Perry", "Katheryn Hudson"], None),
            ("דואה ליפה", ["Dua Lipa"], None),
            ("מיילי סיירוס", ["Miley Cyrus", "Miley"], None),
            ("סלינה גומז", ["Selena Gomez", "Sel Gomez"], None),
            ("הארי סטיילס", ["Harry Styles", "Styles"], None),
            ("סם סמית'", ["Sam Smith", "Samuel Smith"], None),
            ("ג'סטין טימברלייק", ["Justin Timberlake", "Timberlake"], None),
            ("סטיבי וונדר", ["Stevie Wonder", "Stevland Morris"], None),
            ("אלטון ג'ון", ["Elton John", "Reginald Dwight"], None),
            ("פרדי מרקיורי", ["Freddie Mercury", "Farrokh Bulsara"], None),
            ("פול מקרטני", ["Paul McCartney", "McCartney"], None),
            ("ג'ון לנון", ["John Lennon", "Lennon"], None),
            ("בוב דילן", ["Bob Dylan", "Robert Zimmerman"], None),
            ("ברוס ספרינגסטין", ["Bruce Springsteen", "The Boss"], None),
            ("פרנק סינטרה", ["Frank Sinatra", "Sinatra"], None),
            ("אריתה פרנקלין", ["Aretha Franklin", "Aretha"], None),
            ("טינה טרנר", ["Tina Turner", "Anna Mae Bullock"], None),
            ("איימי ויינהאוס", ["Amy Winehouse", "Winehouse"], None),
        ],
    },
    {
        "text": "כתבו שמות של אוכל רחוב בעולם",
        "answers": [
            ("פלאפל", ["Falafel"], None),
            ("שווארמה", ["Shawarma", "Shawurma"], None),
            ("סביח", ["Sabich"], None),
            ("חומוס", ["Hummus", "Houmous"], None),
            ("פיצה", ["Pizza"], None),
            ("נקניקייה בלחמנייה", ["Hot dog", "Hotdog", "הוט דוג"], None),
            ("המבורגר", ["Hamburger", "Burger"], None),
            ("טאקו", ["Taco", "Tacos"], None),
            ("בוריטו", ["Burrito"], None),
            ("קסדייה", ["Quesadilla", "קסדיה"], None),
            ("נאצ'וס", ["Nachos", "נאצוס"], None),
            ("צ'ורוס", ["Churros", "צורוס"], None),
            ("אמפנדה", ["Empanada", "Empanadas"], None),
            ("ארפה", ["Arepa", "Arepas"], None),
            ("סביצ'ה", ["Ceviche", "סביצה"], None),
            ("באן מי", ["Bánh mì", "Banh mi"], None),
            ("פו", ["Phở", "Pho"], None),
            ("פאד תאי", ["Pad Thai", "Phad Thai"], None),
            ("סאטה", ["Satay", "Sate"], None),
            ("נאסי גורנג", ["Nasi goreng"], None),
            ("גיוזה", ["Gyoza", "Gyōza"], None),
            ("טקויאקי", ["Takoyaki"], None),
            ("אוקונומיאקי", ["Okonomiyaki"], None),
            ("ראמן", ["Ramen"], None),
            ("סושי", ["Sushi"], None),
            ("סמוסה", ["Samosa", "Samosas"], None),
            ("פקורה", ["Pakora", "Pakoda"], None),
            ("פאני פורי", ["Pani puri", "Golgappa"], None),
            ("ואדה פאב", ["Vada pav", "Wada pav"], None),
            ("קבב", ["Kebab", "Kabob"], None),
            ("דונר", ["Döner", "Doner kebab"], None),
            ("גירוס", ["Gyros", "Gyro"], None),
            ("סופלקי", ["Souvlaki"], None),
            ("פיש אנד צ'יפס", ["Fish and chips", "Fish & chips"], None),
            ("קרפ", ["Crêpe", "Crepe"], None),
            ("וופל בלגי", ["Belgian waffle", "ופל בלגי"], None),
            ("פרצל", ["Pretzel", "בייגלה גרמני"], None),
            ("פוטין", ["Poutine"], None),
            ("קורן דוג", ["Corn dog", "Corndog"], None),
            ("פירוגי", ["Pierogi", "Pierogies"], None),
        ],
    },
    {
        "text": "כתבו שמות של דמויות מהמיתולוגיה היוונית",
        "answers": [
            ("זאוס", ["Zeus"], None),
            ("הרה", ["Hera"], None),
            ("פוסידון", ["Poseidon", "פוסיידון"], None),
            ("האדס", ["Hades", "היידס"], None),
            ("אתנה", ["Athena", "אתינה"], None),
            ("אפולו", ["Apollo", "אפולון"], None),
            ("ארטמיס", ["Artemis"], None),
            ("אפרודיטה", ["Aphrodite"], None),
            ("ארס", ["Ares"], None),
            ("הרמס", ["Hermes"], None),
            ("הפייסטוס", ["Hephaestus", "הפאיסטוס"], None),
            ("דמטר", ["Demeter", "דמטרה"], None),
            ("דיוניסוס", ["Dionysus", "דיוניסיוס"], None),
            ("הסטיה", ["Hestia"], None),
            ("פרספונה", ["Persephone", "פרספון"], None),
            ("הרקלס", ["Heracles", "Hercules", "הרקולס"], None),
            ("אכילס", ["Achilles", "אכילאוס"], None),
            ("אודיסאוס", ["Odysseus", "Ulysses", "אודיסאוס מלך איתקה"], None),
            ("תסאוס", ["Theseus", "תזאוס"], None),
            ("פרסאוס", ["Perseus"], None),
            ("יאסון", ["Jason", "ג'ייסון"], None),
            ("אורפאוס", ["Orpheus", "אורפיאוס"], None),
            ("פרומתאוס", ["Prometheus"], None),
            ("פנדורה", ["Pandora"], None),
            ("מדוזה", ["Medusa"], None),
            ("המינוטאור", ["Minotaur", "מינוטאור"], None),
            ("הקיקלופ", ["Cyclops", "קיקלופ"], None),
            ("איקרוס", ["Icarus", "איקארוס"], None),
            ("דדלוס", ["Daedalus", "דאידלוס"], None),
            ("מידאס", ["Midas"], None),
            ("נרקיסוס", ["Narcissus"], None),
            ("אדיפוס", ["Oedipus"], None),
            ("אטלס", ["Atlas"], None),
            ("קרונוס", ["Cronus", "Kronos", "כרונוס"], None),
            ("ריאה", ["Rhea"], None),
            ("גאיה", ["Gaia", "Gaea"], None),
            ("אורנוס", ["Uranus", "Ouranos"], None),
            ("כארון", ["Charon", "חרון"], None),
            ("קרברוס", ["Cerberus", "סרברוס"], None),
            ("הלנה מטרויה", ["Helen of Troy", "הלנה"], None),
        ],
    },
    {
        "text": "כתבו שמות של נהרות בעולם",
        "answers": [
            ("הנילוס", ["Nile", "Nile River", "נילוס"], None),
            ("האמזונס", ["Amazon River", "Amazon", "אמזונס"], None),
            ("המיסיסיפי", ["Mississippi River", "Mississippi", "מיסיסיפי"], None),
            ("המיזורי", ["Missouri River", "Missouri", "מיזורי"], None),
            ("היאנגצה", ["Yangtze", "Yangtze River", "יאנגצה"], None),
            ("הנהר הצהוב", ["Yellow River", "Huang He", "הואנג חה"], None),
            ("הגנגס", ["Ganges", "Ganga", "גנגס"], None),
            ("הברהמפוטרה", ["Brahmaputra", "Brahmaputra River", "ברהמפוטרה"], None),
            ("המקונג", ["Mekong", "Mekong River", "מקונג"], None),
            ("האינדוס", ["Indus", "Indus River", "אינדוס"], None),
            ("החידקל", ["Tigris", "Tigris River", "חידקל"], None),
            ("הפרת", ["Euphrates", "Euphrates River", "פרת"], None),
            ("הירדן", ["Jordan River", "River Jordan", "ירדן"], None),
            ("הדנובה", ["Danube", "Danube River", "דנובה"], None),
            ("הריין", ["Rhine", "Rhine River", "ריין"], None),
            ("הוולגה", ["Volga", "Volga River", "וולגה"], None),
            ("התמזה", ["Thames", "River Thames", "תמזה"], None),
            ("הסן", ["Seine", "Seine River", "סן"], None),
            ("הלואר", ["Loire", "Loire River", "לואר"], None),
            ("הרון", ["Rhône", "Rhone", "רון"], None),
            ("האלבה", ["Elbe", "Elbe River", "אלבה"], None),
            ("הפו", ["Po River", "River Po", "פו"], None),
            ("הדנייפר", ["Dnieper", "Dnipro", "דנייפר"], None),
            ("הדון", ["Don River", "River Don", "דון"], None),
            ("הקונגו", ["Congo River", "River Congo", "קונגו"], None),
            ("הניז'ר", ["Niger River", "River Niger", "ניז'ר"], None),
            ("הזמבזי", ["Zambezi", "Zambezi River", "זמבזי"], None),
            ("האורנג'", ["Orange River", "Gariep River", "אורנג'"], None),
            ("הלימפופו", ["Limpopo", "Limpopo River", "לימפופו"], None),
            ("המארי", ["Murray River", "River Murray", "מארי"], None),
            ("הדרלינג", ["Darling River", "River Darling", "דרלינג"], None),
            ("הריו גראנדה", ["Rio Grande", "Río Bravo", "ריו גרנדה"], None),
            ("הקולורדו", ["Colorado River", "River Colorado", "קולורדו"], None),
            ("הקולומביה", ["Columbia River", "River Columbia", "קולומביה"], None),
            ("היוקון", ["Yukon River", "River Yukon", "יוקון"], None),
            ("סנט לורנס", ["Saint Lawrence River", "St. Lawrence River"], None),
            ("הפרנה", ["Paraná River", "Parana River", "פרנה"], None),
            ("האורינוקו", ["Orinoco", "Orinoco River", "אורינוקו"], None),
            ("הלנה", ["Lena River", "River Lena", "לנה"], None),
            ("האוב", ["Ob River", "River Ob", "אוב"], None),
        ],
    },
    {
        "text": "כתבו שמות של שפות מדוברות בעולם",
        "answers": [
            ("עברית", ["Hebrew", "עברית ישראלית"], None),
            ("ערבית", ["Arabic", "ערבית ספרותית"], None),
            ("אנגלית", ["English"], None),
            ("ספרדית", ["Spanish", "Español"], None),
            ("צרפתית", ["French", "Français"], None),
            ("גרמנית", ["German", "Deutsch"], None),
            ("איטלקית", ["Italian", "Italiano"], None),
            ("פורטוגזית", ["Portuguese", "Português"], None),
            ("רוסית", ["Russian", "Русский"], None),
            ("אוקראינית", ["Ukrainian", "Українська"], None),
            ("פולנית", ["Polish", "Polski"], None),
            ("הולנדית", ["Dutch", "Nederlands"], None),
            ("שוודית", ["Swedish", "Svenska"], None),
            ("נורווגית", ["Norwegian", "Norsk"], None),
            ("דנית", ["Danish", "Dansk"], None),
            ("פינית", ["Finnish", "Suomi"], None),
            ("יוונית", ["Greek", "Ελληνικά"], None),
            ("טורקית", ["Turkish", "Türkçe"], None),
            ("פרסית", ["Persian", "Farsi", "פארסית"], None),
            ("הינדי", ["Hindi", "हिन्दी"], None),
            ("אורדו", ["Urdu", "اردو"], None),
            ("בנגלית", ["Bengali", "Bangla"], None),
            ("פנג'אבית", ["Punjabi", "Panjabi"], None),
            ("מנדרינית", ["Mandarin Chinese", "Mandarin", "סינית מנדרינית"], None),
            ("יפנית", ["Japanese", "日本語"], None),
            ("קוריאנית", ["Korean", "한국어"], None),
            ("וייטנאמית", ["Vietnamese", "Tiếng Việt", "ויאטנמית"], None),
            ("תאית", ["Thai", "ภาษาไทย"], None),
            ("אינדונזית", ["Indonesian", "Bahasa Indonesia"], None),
            ("מלאית", ["Malay", "Bahasa Melayu"], None),
            ("סוואהילית", ["Swahili", "Kiswahili"], None),
            ("אמהרית", ["Amharic", "አማርኛ"], None),
            ("יורובה", ["Yoruba", "Yorùbá"], None),
            ("זולו", ["Zulu", "isiZulu"], None),
            ("אפריקאנס", ["Afrikaans"], None),
            ("רומנית", ["Romanian", "Română"], None),
            ("הונגרית", ["Hungarian", "Magyar"], None),
            ("צ'כית", ["Czech", "Čeština"], None),
            ("סלובקית", ["Slovak", "Slovenčina"], None),
            ("אספרנטו", ["Esperanto"], None),
        ],
    },
    {
        "text": "כתבו שמות של סוגי גבינות",
        "answers": [
            ("צ'דר", ["Cheddar", "Cheddar cheese"], None),
            ("מוצרלה", ["Mozzarella", "Mozzarella cheese"], None),
            ("פרמזן", ["Parmesan", "Parmigiano Reggiano"], None),
            ("גאודה", ["Gouda", "Gouda cheese"], None),
            ("ברי", ["Brie", "Brie cheese"], None),
            ("קממבר", ["Camembert", "Camembert cheese"], None),
            ("רוקפור", ["Roquefort", "Roquefort cheese"], None),
            ("פטה", ["Feta", "Feta cheese"], None),
            ("חלומי", ["Halloumi", "Haloumi"], None),
            ("ריקוטה", ["Ricotta", "Ricotta cheese"], None),
            ("מסקרפונה", ["Mascarpone", "Mascarpone cheese"], None),
            ("פקורינו רומנו", ["Pecorino Romano", "Pecorino"], None),
            ("גרוייר", ["Gruyère", "Gruyere"], None),
            ("אמנטל", ["Emmental", "Emmentaler"], None),
            ("מנצ'גו", ["Manchego", "Manchego cheese"], None),
            ("גורגונזולה", ["Gorgonzola", "Gorgonzola cheese"], None),
            ("סטילטון", ["Stilton", "Stilton cheese"], None),
            ("פרובולונה", ["Provolone", "Provolone cheese"], None),
            ("בוראטה", ["Burrata", "Burrata cheese"], None),
            ("שבר", ["Chèvre", "Chevre", "גבינת עיזים צרפתית"], None),
            ("גבינת שמנת", ["Cream cheese", "קרים צ'יז"], None),
            ("קוטג'", ["Cottage cheese", "קוטג"], None),
            ("לבנה", ["Labneh", "Labaneh"], None),
            ("קסו פרסקו", ["Queso fresco", "Queso fresco cheese"], None),
            ("מונטריי ג'ק", ["Monterey Jack", "Jack cheese"], None),
            ("קולבי", ["Colby", "Colby cheese"], None),
            ("אדם", ["Edam", "Edam cheese"], None),
            ("הווארטי", ["Havarti", "Havarti cheese"], None),
            ("מונסטר", ["Munster", "Munster cheese"], None),
            ("טלג'יו", ["Taleggio", "Taleggio cheese"], None),
            ("אסיאגו", ["Asiago", "Asiago cheese"], None),
            ("פונטינה", ["Fontina", "Fontina cheese"], None),
            ("קונטה", ["Comté", "Comte"], None),
            ("רבלושון", ["Reblochon", "Reblochon cheese"], None),
            ("רקלט", ["Raclette", "Raclette cheese"], None),
            ("לימבורגר", ["Limburger", "Limburger cheese"], None),
            ("פניר", ["Paneer", "Indian cottage cheese"], None),
            ("קוטיחה", ["Cotija", "Cotija cheese"], None),
            ("אואחאקה", ["Oaxaca cheese", "Quesillo"], None),
            ("טילזיט", ["Tilsit", "Tilsiter"], None),
        ],
    },
]


QUESTION_SOURCES_V10: dict[str, list[str]] = {
    "כתבו מילים בסלנג ישראלי": [
        "https://en.wiktionary.org/wiki/Category:Hebrew_slang",
    ],
    "כתבו דברים שיש במקרר": [
        "https://www.foodsafety.gov/food-safety-charts/cold-food-storage-charts",
    ],
    "כתבו דברים שלוקחים לים": [
        "https://www.rei.com/learn/expert-advice/beach-checklist.html",
    ],
    "כתבו שמות של תוכניות ריאליטי": [
        "https://en.wikipedia.org/wiki/List_of_programs_broadcast_by_Channel_2_(Israel)",
    ],
    'כתבו שמות של דמויות מהתנ"ך': [
        "https://en.wikipedia.org/wiki/List_of_major_biblical_figures",
    ],
    "כתבו שמות של דמויות מהארי פוטר": [
        "https://en.wikipedia.org/wiki/List_of_Harry_Potter_characters",
    ],
    "כתבו שמות של זמרים בינלאומיים": [
        "https://en.wikipedia.org/wiki/List_of_best-selling_music_artists",
    ],
    "כתבו שמות של אוכל רחוב בעולם": [
        "https://en.wikipedia.org/wiki/List_of_street_foods",
    ],
    "כתבו שמות של דמויות מהמיתולוגיה היוונית": [
        "https://en.wikipedia.org/wiki/Lists_of_Greek_mythological_figures",
    ],
    "כתבו שמות של נהרות בעולם": [
        "https://en.wikipedia.org/wiki/Lists_of_rivers",
    ],
    "כתבו שמות של שפות מדוברות בעולם": [
        "https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers",
    ],
    "כתבו שמות של סוגי גבינות": [
        "https://en.wikipedia.org/wiki/List_of_cheeses",
    ],
}
