// Generated by backend/scripts/generate_protocol_types.py. Do not edit.

export interface SubmitAnswerCommand {
  type: "submit_answer";
  client_command_id: string;
  text: string;
}

export interface PingCommand {
  type: "ping";
}

export type ClientCommand = SubmitAnswerCommand | PingCommand;

export interface ServerEventEnvelope {
  event_id: string;
  event_type: string;
  protocol_version: number;
  server_timestamp: string;
  server_now_ms: number;
  match_id: string;
  type: string;
  seq: number;
  payload: Record<string, unknown>;
  [key: string]: unknown;
}
